### ISSUE TITLE
Retrieve file owner info/file metadata with RPA.FileSystem library

### ISSUE THREAD

**Issue by ndsulit** [robocorp/rpaframework#101]
Is there any way to retrieve the file owner info/file metadata with the RPA.FileSystem library?

**Comment by osrjv** [comment]
No, there is no existing keyword for this, but it seemed trivial to implement so I added it in commit 2a03ac94f39e9155d6aa1f29853c7341df849125. It'll be in the next release.

Just a note for the future, the issue tracker is for bug reports and more fleshed out feature requests. If you want to ask general questions or get support, I recommend either Robocorp's [forum](https://forum.robocorp.com/) or [Slack](https://robocorp-developers.slack.com/).
