### ISSUE TITLE
`RPA.Email.ImapSmtp` appears to handle the To, CC, and BCC fields in an unexpected way

### ISSUE THREAD

**Issue by TimothyLopas** [robocorp/rpaframework#1053]
```python
        if cc:
            msg["Cc"] = ",".join(cc) if isinstance(cc, list) else cc
            recipients += cc if isinstance(cc, list) else cc.split(",")
        if bcc:
            recipients += bcc if isinstance(bcc, list) else bcc.split(",")
```

Lines 650 - 654 appear to do the following unexpected things:
- Merging the cc and bcc list into the recipients list. The returned recipients list is used in send_message as the To line which can result in an incorrect To field.
- The bcc section doesn't appear to add the bcc list to the MIMEType. This appears to be handled in the cc section though.
- The combination of the above unexpected behaviors would indicate that if a user only adds addresses to the bcc field then all email addresses will actually be sent via the To field.

**Comment by cmin764** [comment]
Indeed, it looks like the MIME parts were started to be added [here](https://github.com/robocorp/rpaframework/pull/948/files#diff-3f1032f10774f2fa7b3a18e016d263f8f45335aeef634ac150ee8172084a2c06R577-R586) as part of **[23.0.0](https://updates.robocorp.com/release/AcIcC-rpa-framework-2300)**.

So maybe we should to the following change:
Keep the `To` part separate from `Cc` and `Bcc` and test if they really do what they intend to do.
  - `To`: visible to everybody
  - `Cc`: visible copies
  - `Bcc`: hidden copies
