### ISSUE TITLE
Compatibility issue: rpaframework-dialogs not updated and still requiring robotframework <6.0.0

### ISSUE THREAD

**Issue by axiom41** [robocorp/rpaframework#1070]
Hello.
After updating rpaframework to 26.1.0, the following error appeared:

`rpaframework-dialogs 4.0.4 requires robotframework!=4.0.1,<6.0.0,>=4.0.0, but you have robotframework 6.1.1 which is incompatible.`

Please update this package too.

**Comment by mikahanninen** [comment]
The `rpaframework-dialogs` library has been deprecated since **22.0.0** and we recommend using `rpaframework-assistant` instead.

**Comment by mikahanninen** [comment]
There is a [migration guide](https://github.com/robocorp/rpaframework/blob/master/packages/assistant/docs/Migration-Guide.md) and of course the [RPA.Assistant](https://robocorp.com/docs/libraries/rpa-framework/rpa-assistant) documentation pages.

**Comment by axiom41** [comment]
Thanks @mikahanninen 
Will follow the guide, as suggested ;-)

**Comment by mikahanninen** [comment]
And finally here are the Portal [bots](https://robocorp.com/portal/library/rpa-assistant) utilizing `RPA.Assistant` library.
