### ISSUE TITLE
Dependency float problems

### ISSUE THREAD

**Issue by xylix** [robocorp/rpaframework#108]
- [x] Our CI should test against `pip install rpaframework` probably nightly and against some of the biggest versions to catch problems where floating subdependencies break user setup
- [ ] Do scripted analysis to figure out which of our dependencies lack pinnings for their dependencies major dependencies and figure out if fixing this case by case is a good solution

**Comment by tonnitommi** [comment]
@osrjv This have been open for 2´years, time to close? :)

**Comment by osrjv** [comment]
It's still a valid concern, but it's one of those things which we either fix immediately or re-open if it becomes more critical. So close for now.
