### ISSUE TITLE
Enabling Truststore in Python 3.10

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#1083]
- conditional package installation
- checking python and pip versions
- early implementation into `core` package

**Comment by cmin764** [comment]
There might be other parts earlier in the process which can pose a risk of importing urllib/requests earlier:

- `python -m robot ...` CLI entrypoint which runs the robot file:
   - ```
      cmin@robocorp-mac robot % grep -rni "aiohttp" *
      cmin@robocorp-mac robot % grep -rni "urllib" *
      libdocpkg/htmlutils.py:18:    from urllib import quote
      libdocpkg/htmlutils.py:20:    from urllib.parse import quote
      Binary file utils/__pycache__/robotpath.cpython-39.pyc matches
      utils/robotpath.py:19:from urllib.request import pathname2url as path_to_url
      cmin@robocorp-mac robot % grep -rni "requests" *
      libraries/Remote.py:257:# http://stackoverflow.com/questions/2425799/timeout-for-xmlrpclib-client-requests
      ```
- `Library       <RF-lib>` placed before any of our `RPA.*` libs, like:
   - `RequestsLibrary`
- Cases when `rpaframework` isn't installed at all, but maybe it should if the user wants to benefit from this patch.

### Potential solutions
1. Change the `python -m robot` entry-point into something like `python -m RPA.robot` so it will be something controlled by us. (this way we initialize the injection prior to any call) -- drawback: requires `rpaframework-core` installed and changes in **rcc** and templates
2. Fork the `robotframework` package and to the importing and initializing from there. -- drawback: requires `rpaframework-core` and the fork itself + package maintenance
