### ISSUE TITLE
New rpaframework-core not compatible with rpaframework

### ISSUE THREAD

**Issue by axiom41** [robocorp/rpaframework#1089]
Hello.
Updating rpaframework and rpaframework-core to the latest versions (both released today), i get the following error:

`rpaframework 26.1.1 requires rpaframework-core==11.0.6, but you have rpaframework-core 11.1.1 which is incompatible.`

Please check and align the package versions.

Many thanks in advance for your support.

**Comment by mikahanninen** [comment]
What you have in your conda.yaml ?

**Comment by axiom41** [comment]
Hi.
Where is the "conda.yaml" to look for?

I can see the following line in my "...\Lib\site-packages\rpaframework-26.1.1.dist-info\METADATA":

`Requires-Dist: rpaframework-core (==11.0.6)`

I'm on Win11 x64 / Python 3.11.5 and installed rpaframework from the following command, to have a "fresh" installation, without cached packages:

`pip install -U --no-cache-dir --force rpaframework`

Installing rpaframework-core after that, generated the error

**Comment by mikahanninen** [comment]
`rpaframework-core` package is not meant to be installed separately so there won't be any support if such installation is done

> This package is a set of core functionality and utilities used by [RPA Framework](https://rpaframework.org/). It is not intended to be installed directly, but as a dependency to other projects.
