### ISSUE TITLE
import Imapsmtp - error: cannot import name 'OxmlElement' from 'docx.oxml'

### ISSUE THREAD

**Issue by bednarczyk9** [robocorp/rpaframework#1112]
I receive issue as below for diffrent versions of rpaframework. I tested it also for rpaframework==27.3.1. To avoid it I had to add python-docx==0.8.11 to conda.yaml.
 
![image](https://github.com/robocorp/rpaframework/assets/116433520/499fbc18-e3ac-4100-9681-5513f286e150)

**Comment by mikahanninen** [comment]
Hi @bednarczyk9 thank you reporting this issue.

We have already addressed this issue through an [update](https://updates.robocorp.com/release/wGB6C-issue-with-rpaemailimapsmtp-and-rparobocorpworkitems-libraries)
