### ISSUE TITLE
Add support for inspecting Selenium network requests/responses

### ISSUE THREAD

**Issue by osrjv** [robocorp/rpaframework#113]
As the title suggests, if feasible to implement the Selenium library should have keywords for inspecting network traffic, e.g. reading response headers. This would bring some parity between it and Playwright.

**Comment by cmin764** [comment]
Removed this from the Roadmap as it doesn't look like this was requested too often. (but keeping it for tracking purposes)

**Comment by tonnitommi** [comment]
Possible to do with Chrome Dev Tools Protocol (@mikahanninen has the example). No customer requests enough to justify implementation.
