### ISSUE TITLE
Fail to install rpaframework in Windows 10 Pro

### ISSUE THREAD

**Issue by darkb0ts** [robocorp/rpaframework#1148]
python version:  Python 3.12.1

vsc code error:  $ python rpa_frame_work.py 
Traceback (most recent call last):
  File "D:\rpa_framework\rpa_frame_work.py", line 2, in <module>
    from rpaframework import Browser, Desktop, Excel, Email     
ModuleNotFoundError: No module named 'rpaframework'
(.venv)

command  line: 
$ pip install rpaframework
Collecting rpaframework
  Using cached rpaframework-28.1.0-py3-none-any.whl.metadata (32 kB)
Collecting O365<2.0.27,>=2.0.21 (from rpaframework)
  Using cached O365-2.0.26-py3-none-any.whl (163 kB)
Collecting PyJWT<3.0.0,>=2.6.0 (from rpaframework)
  Using cached PyJWT-2.8.0-py3-none-any.whl.metadata (4.2 kB)
Collecting PySocks!=1.5.7,<2.0.0,>=1.5.6 (from rpaframework)
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting PyYAML<7.0.0,>=5.4.1 (from rpaframework)
  Using cached PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting beautifulsoup4<5.0.0,>=4.7.0 (from rpaframework)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting chardet<4.0.0,>=3.0.0 (from rpaframework)
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting click<9.0.0,>=8.1.2 (from rpaframework)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting comtypes<2.0.0,>=1.1.11 (from rpaframework)
  Using cached comtypes-1.2.1-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting cryptography<42.0.0,>=41.0.3 (from rpaframework)
  Using cached cryptography-41.0.7-cp37-abi3-win_amd64.whl.metadata (5.3 kB)
Collecting docutils (from rpaframework)
  Using cached docutils-0.20.1-py3-none-any.whl.metadata (2.8 kB)
Collecting exchangelib<5.0.0,>=4.7.6 (from rpaframework)
  Using cached exchangelib-4.9.0-py2.py3-none-any.whl (251 kB)
Collecting graphviz<0.14.0,>=0.13.2 (from rpaframework)
  Using cached graphviz-0.13.2-py2.py3-none-any.whl (17 kB)
Collecting holidays<0.22,>=0.21 (from rpaframework)
  Using cached holidays-0.21.13-py3-none-any.whl (378 kB)
Collecting htmldocx<0.0.7,>=0.0.6 (from rpaframework)
  Using cached htmldocx-0.0.6-py3-none-any.whl (9.5 kB)
Collecting importlib-metadata>=4.13.0 (from rpaframework)
  Using cached importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting java-access-bridge-wrapper<2.0.0,>=1.1.0 (from rpaframework)
  Using cached java_access_bridge_wrapper-1.1.0-py3-none-any.whl.metadata (5.4 kB)
Collecting jsonpath-ng<2.0.0,>=1.5.2 (from rpaframework)
  Using cached jsonpath_ng-1.6.1-py3-none-any.whl.metadata (18 kB)
Collecting mss<7.0.0,>=6.0.0 (from rpaframework)
  Using cached mss-6.1.0-py3-none-any.whl (76 kB)
Collecting netsuitesdk<2.0.0,>=1.1.0 (from rpaframework)
  Using cached netsuitesdk-1.24.0-py3-none-any.whl (31 kB)
Collecting notifiers<2.0.0,>=1.3.3 (from rpaframework)
  Using cached notifiers-1.3.3-py3-none-any.whl (43 kB)
Collecting oauthlib<4.0.0,>=3.2.2 (from rpaframework)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Collecting openpyxl<4.0.0,>=3.0.9 (from rpaframework)
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting pendulum<3.0.0,>=2.1.2 (from rpaframework)
  Using cached pendulum-2.1.2.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow<11.0.0,>=10.0.1 (from rpaframework)
  Using cached pillow-10.2.0-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting psutil<6.0.0,>=5.7.0 (from rpaframework)
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting pynput-robocorp-fork<6.0.0,>=5.0.0 (from rpaframework)
  Using cached pynput_robocorp_fork-5.0.0-py2.py3-none-any.whl (84 kB)
Collecting pyotp<3.0.0,>=2.6.0 (from rpaframework)
  Using cached pyotp-2.9.0-py3-none-any.whl.metadata (9.8 kB)
Collecting pyperclip<2.0.0,>=1.8.0 (from rpaframework)
  Using cached pyperclip-1.8.2-py3-none-any.whl
Collecting python-docx<0.9.0,>=0.8.11 (from rpaframework)
  Using cached python_docx-0.8.11-py3-none-any.whl
Collecting pywin32<307,>=302 (from rpaframework)
  Using cached pywin32-306-cp312-cp312-win_amd64.whl (9.2 MB)
Collecting pywinauto<0.7.0,>=0.6.8 (from rpaframework)
  Using cached pywinauto-0.6.8-py2.py3-none-any.whl (362 kB)
Collecting requests<3.0.0,>=2.28.1 (from rpaframework)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-oauthlib<2.0.0,>=1.3.1 (from rpaframework)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting robocorp-storage<2.0.0,>=1.0.2 (from rpaframework)
  Using cached robocorp_storage-1.0.3-py3-none-any.whl.metadata (1.9 kB)
Collecting robotframework!=4.0.1,!=6.1.0,<7.0.0,>=4.0.0 (from rpaframework)
  Using cached robotframework-6.1.1-py3-none-any.whl.metadata (7.5 kB)
Collecting robotframework-pythonlibcore<5.0.0,>=4.2.0 (from rpaframework)
  Using cached robotframework_pythonlibcore-4.3.0-py2.py3-none-any.whl.metadata (6.0 kB)
Collecting robotframework-requests<0.10.0,>=0.9.1 (from rpaframework)
  Using cached robotframework_requests-0.9.6-py3-none-any.whl.metadata (7.2 kB)
Collecting robotframework-sapguilibrary<2.0,>=1.1 (from rpaframework)
  Using cached robotframework_sapguilibrary-1.1-py3-none-any.whl
Collecting robotframework-seleniumlibrary<7.0.0,>=6.0.0 (from rpaframework)
  Using cached robotframework_seleniumlibrary-6.2.0-py2.py3-none-any.whl.metadata (15 kB)
Collecting robotframework-seleniumtestability<3.0.0,>=2.0.0 (from rpaframework)
  Using cached robotframework_seleniumtestability-2.1.0-py3-none-any.whl (23 kB)
Collecting rpaframework-core<12.0.0,>=11.3.0 (from rpaframework)
  Using cached rpaframework_core-11.3.0-py3-none-any.whl.metadata (1.8 kB)
Collecting rpaframework-pdf<8.0.0,>=7.3.0 (from rpaframework)
  Using cached rpaframework_pdf-7.3.1-py3-none-any.whl.metadata (1.6 kB)
Collecting rpaframework-windows<8.0.0,>=7.5.0 (from rpaframework)
  Using cached rpaframework_windows-7.5.0-py3-none-any.whl.metadata (2.1 kB)
Collecting selenium==4.15.2 (from rpaframework)
  Using cached selenium-4.15.2-py3-none-any.whl.metadata (6.9 kB)
Collecting simple_salesforce<2.0.0,>=1.0.0 (from rpaframework)
  Using cached simple_salesforce-1.12.5-py2.py3-none-any.whl.metadata (29 kB)
Collecting smartsheet-python-sdk<4.0.0,>=3.0.0 (from rpaframework)
  Using cached smartsheet_python_sdk-3.0.2-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting tenacity<9.0.0,>=8.0.1 (from rpaframework)
  Using cached tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting tweepy<4.0.0,>=3.8.0 (from rpaframework)
  Using cached tweepy-3.10.0-py2.py3-none-any.whl (30 kB)
Collecting tzlocal<5.0,>=4.2 (from rpaframework)
  Using cached tzlocal-4.3.1-py3-none-any.whl.metadata (14 kB)
Collecting validators<0.21.0,>=0.20.0 (from rpaframework)
  Using cached validators-0.20.0-py3-none-any.whl
Collecting xlrd<3.0.0,>=2.0.1 (from rpaframework)
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Collecting xlutils<3.0.0,>=2.0.0 (from rpaframework)
  Using cached xlutils-2.0.0-py2.py3-none-any.whl (55 kB)
Collecting xlwt<2.0.0,>=1.3.0 (from rpaframework)
  Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Collecting urllib3<3,>=1.26 (from urllib3[socks]<3,>=1.26->selenium==4.15.2->rpaframework)
  Using cached urllib3-2.2.0-py3-none-any.whl.metadata (6.4 kB)
Collecting trio~=0.17 (from selenium==4.15.2->rpaframework)
  Using cached trio-0.24.0-py3-none-any.whl.metadata (4.9 kB)
Collecting trio-websocket~=0.9 (from selenium==4.15.2->rpaframework)
  Using cached trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi>=2021.10.8 (from selenium==4.15.2->rpaframework)
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4<5.0.0,>=4.7.0->rpaframework)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting colorama (from click<9.0.0,>=8.1.2->rpaframework)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting cffi>=1.12 (from cryptography<42.0.0,>=41.0.3->rpaframework)
  Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting cached-property (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting defusedxml>=0.6.0 (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting dnspython>=2.0.0 (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached dnspython-2.5.0-py3-none-any.whl.metadata (5.8 kB)
Collecting isodate (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached isodate-0.6.1-py2.py3-none-any.whl (41 kB)
Collecting lxml>3.0 (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached lxml-5.1.0-cp312-cp312-win_amd64.whl.metadata (3.6 kB)
Collecting pygments (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting requests-ntlm>=0.2.0 (from exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached requests_ntlm-1.2.0-py3-none-any.whl (6.0 kB)
Requirement already satisfied: tzdata in d:\rpa_framework\.venv\lib\site-packages (from exchangelib<5.0.0,>=4.7.6->rpaframework) (2023.4)
Collecting PyMeeus (from holidays<0.22,>=0.21->rpaframework)
  Using cached PyMeeus-0.5.12-py3-none-any.whl
Collecting convertdate>=2.3.0 (from holidays<0.22,>=0.21->rpaframework)
  Using cached convertdate-2.4.0-py3-none-any.whl (47 kB)
Collecting hijri-converter (from holidays<0.22,>=0.21->rpaframework)
  Using cached hijri_converter-2.3.1-py3-none-any.whl (13 kB)
Collecting korean-lunar-calendar (from holidays<0.22,>=0.21->rpaframework)
  Using cached korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Requirement already satisfied: python-dateutil in d:\rpa_framework\.venv\lib\site-packages (from holidays<0.22,>=0.21->rpaframework) (2.8.2)
Collecting zipp>=0.5 (from importlib-metadata>=4.13.0->rpaframework)
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting ply (from jsonpath-ng<2.0.0,>=1.5.2->rpaframework)
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting zeep (from netsuitesdk<2.0.0,>=1.1.0->rpaframework)
  Using cached zeep-4.2.1-py3-none-any.whl (101 kB)
Collecting jsonschema<5.0.0,>=4.4.0 (from notifiers<2.0.0,>=1.3.3->rpaframework)
  Using cached jsonschema-4.21.1-py3-none-any.whl.metadata (7.8 kB)
Collecting pytz>=2018.5 (from O365<2.0.27,>=2.0.21->rpaframework)
  Using cached pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Collecting stringcase>=1.2.0 (from O365<2.0.27,>=2.0.21->rpaframework)
  Using cached stringcase-1.2.0-py3-none-any.whl
Collecting et-xmlfile (from openpyxl<4.0.0,>=3.0.9->rpaframework)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Collecting pytzdata>=2020.1 (from pendulum<3.0.0,>=2.1.2->rpaframework)
  Using cached pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
Requirement already satisfied: six in d:\rpa_framework\.venv\lib\site-packages (from pynput-robocorp-fork<6.0.0,>=5.0.0->rpaframework) (1.16.0)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.28.1->rpaframework)
  Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.28.1->rpaframework)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting furl (from robotframework-seleniumtestability<3.0.0,>=2.0.0->rpaframework)
  Using cached furl-2.1.3-py2.py3-none-any.whl (20 kB)
Collecting wrapt (from robotframework-seleniumtestability<3.0.0,>=2.0.0->rpaframework)
  Using cached wrapt-1.16.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
Collecting packaging<24.0,>=23.1 (from rpaframework-core<12.0.0,>=11.3.0->rpaframework)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting uiautomation<3.0.0,>=2.0.15 (from rpaframework-core<12.0.0,>=11.3.0->rpaframework)
  Using cached uiautomation-2.0.18-py3-none-any.whl (159 kB)
Collecting webdriver-manager==4.0.1 (from rpaframework-core<12.0.0,>=11.3.0->rpaframework)
  Using cached webdriver_manager-4.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting python-dotenv (from webdriver-manager==4.0.1->rpaframework-core<12.0.0,>=11.3.0->rpaframework)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting fpdf2<3.0.0,>=2.7.5 (from rpaframework-pdf<8.0.0,>=7.3.0->rpaframework)
  Using cached fpdf2-2.7.7-py2.py3-none-any.whl.metadata (55 kB)
Collecting pdfminer.six==20221105 (from rpaframework-pdf<8.0.0,>=7.3.0->rpaframework)
  Using cached pdfminer.six-20221105-py3-none-any.whl (5.6 MB)
Collecting pypdf<4.0.0,>=3.16.2 (from rpaframework-pdf<8.0.0,>=7.3.0->rpaframework)
  Using cached pypdf-3.17.4-py3-none-any.whl.metadata (7.5 kB)
Collecting fire<0.5.0,>=0.4.0 (from rpaframework-windows<8.0.0,>=7.5.0->rpaframework)
  Using cached fire-0.4.0-py2.py3-none-any.whl
Collecting more-itertools (from simple_salesforce<2.0.0,>=1.0.0->rpaframework)
  Using cached more_itertools-10.2.0-py3-none-any.whl.metadata (34 kB)
Collecting requests-toolbelt (from smartsheet-python-sdk<4.0.0,>=3.0.0->rpaframework)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Collecting pytz-deprecation-shim (from tzlocal<5.0,>=4.2->rpaframework)
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting decorator>=3.4.0 (from validators<0.21.0,>=0.20.0->rpaframework)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pycparser (from cffi>=1.12->cryptography<42.0.0,>=41.0.3->rpaframework)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting termcolor (from fire<0.5.0,>=0.4.0->rpaframework-windows<8.0.0,>=7.5.0->rpaframework)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting fonttools>=4.34.0 (from fpdf2<3.0.0,>=2.7.5->rpaframework-pdf<8.0.0,>=7.3.0->rpaframework)
  Using cached fonttools-4.47.2-cp312-cp312-win_amd64.whl.metadata (160 kB)
Collecting attrs>=22.2.0 (from jsonschema<5.0.0,>=4.4.0->notifiers<2.0.0,>=1.3.3->rpaframework)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema<5.0.0,>=4.4.0->notifiers<2.0.0,>=1.3.3->rpaframework)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema<5.0.0,>=4.4.0->notifiers<2.0.0,>=1.3.3->rpaframework)
  Using cached referencing-0.33.0-py3-none-any.whl.metadata (2.7 kB)
Collecting rpds-py>=0.7.1 (from jsonschema<5.0.0,>=4.4.0->notifiers<2.0.0,>=1.3.3->rpaframework)
  Using cached rpds_py-0.17.1-cp312-none-win_amd64.whl.metadata (4.2 kB)
Collecting pyspnego>=0.1.6 (from requests-ntlm>=0.2.0->exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached pyspnego-0.10.2-py3-none-any.whl.metadata (5.4 kB)
Collecting sortedcontainers (from trio~=0.17->selenium==4.15.2->rpaframework)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome (from trio~=0.17->selenium==4.15.2->rpaframework)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio~=0.17->selenium==4.15.2->rpaframework)
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium==4.15.2->rpaframework)
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting orderedmultidict>=1.0.1 (from furl->robotframework-seleniumtestability<3.0.0,>=2.0.0->rpaframework)
  Using cached orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Collecting platformdirs>=1.4.0 (from zeep->netsuitesdk<2.0.0,>=1.1.0->rpaframework)
  Using cached platformdirs-4.2.0-py3-none-any.whl.metadata (11 kB)
Collecting requests-file>=1.5.1 (from zeep->netsuitesdk<2.0.0,>=1.1.0->rpaframework)
  Using cached requests_file-2.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting sspilib>=0.1.0 (from pyspnego>=0.1.6->requests-ntlm>=0.2.0->exchangelib<5.0.0,>=4.7.6->rpaframework)
  Using cached sspilib-0.1.0-cp312-cp312-win_amd64.whl.metadata (7.4 kB)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.15.2->rpaframework)
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached rpaframework-28.1.0-py3-none-any.whl (681 kB)
Using cached selenium-4.15.2-py3-none-any.whl (10.2 MB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached comtypes-1.2.1-py2.py3-none-any.whl (184 kB)
Using cached cryptography-41.0.7-cp37-abi3-win_amd64.whl (2.7 MB)
Using cached importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Using cached java_access_bridge_wrapper-1.1.0-py3-none-any.whl (32 kB)
Using cached jsonpath_ng-1.6.1-py3-none-any.whl (29 kB)
Using cached pillow-10.2.0-cp312-cp312-win_amd64.whl (2.6 MB)
Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
Using cached pyotp-2.9.0-py3-none-any.whl (13 kB)
Using cached PyYAML-6.0.1-cp312-cp312-win_amd64.whl (138 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached robocorp_storage-1.0.3-py3-none-any.whl (11 kB)
Using cached robotframework-6.1.1-py3-none-any.whl (699 kB)
Using cached robotframework_pythonlibcore-4.3.0-py2.py3-none-any.whl (10 kB)
Using cached robotframework_requests-0.9.6-py3-none-any.whl (21 kB)
Using cached robotframework_seleniumlibrary-6.2.0-py2.py3-none-any.whl (95 kB)
Using cached rpaframework_core-11.3.0-py3-none-any.whl (49 kB)
Using cached webdriver_manager-4.0.1-py2.py3-none-any.whl (27 kB)
Using cached rpaframework_pdf-7.3.1-py3-none-any.whl (622 kB)
Using cached rpaframework_windows-7.5.0-py3-none-any.whl (49 kB)
Using cached simple_salesforce-1.12.5-py2.py3-none-any.whl (128 kB)
Using cached smartsheet_python_sdk-3.0.2-py2.py3-none-any.whl (229 kB)
Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Using cached tzlocal-4.3.1-py3-none-any.whl (20 kB)
Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached cffi-1.16.0-cp312-cp312-win_amd64.whl (181 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
Using cached dnspython-2.5.0-py3-none-any.whl (305 kB)
Using cached fpdf2-2.7.7-py2.py3-none-any.whl (193 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached jsonschema-4.21.1-py3-none-any.whl (85 kB)
Using cached lxml-5.1.0-cp312-cp312-win_amd64.whl (3.9 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached pypdf-3.17.4-py3-none-any.whl (278 kB)
Using cached pytz-2023.4-py2.py3-none-any.whl (506 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached trio-0.24.0-py3-none-any.whl (460 kB)
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Using cached urllib3-2.2.0-py3-none-any.whl (120 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Using cached more_itertools-10.2.0-py3-none-any.whl (57 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached wrapt-1.16.0-cp312-cp312-win_amd64.whl (37 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached fonttools-4.47.2-cp312-cp312-win_amd64.whl (2.2 MB)
Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Using cached platformdirs-4.2.0-py3-none-any.whl (17 kB)
Using cached pyspnego-0.10.2-py3-none-any.whl (129 kB)
Using cached referencing-0.33.0-py3-none-any.whl (26 kB)
Using cached requests_file-2.0.0-py2.py3-none-any.whl (4.2 kB)
Using cached rpds_py-0.17.1-cp312-none-win_amd64.whl (205 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Using cached sspilib-0.1.0-cp312-cp312-win_amd64.whl (567 kB)
Building wheels for collected packages: pendulum
  Building wheel for pendulum (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pendulum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-4n7sp8xb\pendulum_6c367568f8924d53bb87fc56512b353e\build.py", line 5, in <module>
          from distutils.command.build_ext import build_ext
      ModuleNotFoundError: No module named 'distutils'
      Traceback (most recent call last):
        File "D:\rpa_framework\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\rpa_framework\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\rpa_framework\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-x_93h827\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-x_93h827\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-x_93h827\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 123, in build
          self._build(zip_file)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-x_93h827\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-x_93h827\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 266, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:/rpa_framework/.venv/Scripts/python.exe', 'build.py']' returned non-zero 
exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects
(.venv) 

And try install distutils on cmd                                                                                    
 $ pip install distutils                                                                                                    
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils
(.venv)

**Comment by mikahanninen** [comment]
Our recommended Python version is `3.10.12` as indicated in our templates, as an example Python [template](https://github.com/robocorp/template-python).

Newer Python versions run a risk of lack of support in packages as indicated by the https://pyreadiness.org/3.10 (overall support level 77.2%) compared to https://pyreadiness.org/3.12 (overall support level 46.7%).

Just tried with `Python=3.11.7` and `rpaframework` was successfully installed for that.
