### ISSUE TITLE
RPA.Dialogs close detection

### ISSUE THREAD

**Issue by ete99** [robocorp/rpaframework#115]
This is my first time writing an Issue so please tell me if I can do anything better.

While testing Dialogs prompt I've noticed that if you close the browser the script stays halted waiting for user input, but since the browser is closed and the server keeps running the only way to break out is to force stop the script or to open again the browser in the respective served url and complete the form (which is unlikely that a user will do).
My idea to solve this is to open a new browser by checking in the function request_response this:
```
            ...
            while True:
                # if etag:
                #    headers['If-None-Match'] = etag
                try:
                    br.driver.current_window_handle  # If closed raise an exception 
                except:
                    br.open_available_browser(f"{self.server_address}/form.html")  # Open browser again
                    br.set_window_size(window_width, window_height)
                ...
```

**Comment by osrjv** [comment]
Hi, thanks for the report! Seems to be quite straightforward, and I was actually convinced it had a check for that case already, but apparently not. I'll take it under work and try to get it into the next release.

PS. You reminded me of the fact that we don't have issue templates in this repository yet, will have to sort that out too

**Comment by ete99** [comment]
Great, thank you!

**Comment by osrjv** [comment]
I decided to fail the keyword if a user closes the browser since I think it's the clearest "cancel" they can send in that situation. Constantly re-opening the browser would seem a bit hostile, in my mind.

For the issue of hanging forever (for instance, if the browser is left open without a submit) I added a timeout argument. For backwards compatibility, it's now infinite by default.
