### ISSUE TITLE
RPA tests not running when the physical display or virtual display is locked

### ISSUE THREAD

**Issue by revathikanakachalam** [robocorp/rpaframework#1153]
We are using RPA.Windows library for our windows application automation. The tests are not running when the display physical or virtual is locked. It says **"Make sure tests are run with a physical or virtual display."** Is there any workaround to make the tests run without physical or virtual display? Or Is there a way to make tests to work when screen is locked?

Appreciate any help

**Comment by raivolink** [comment]
RPA.Windows and application automation frameworks in general need presence and access to user interfaces.

**Comment by revathikanakachalam** [comment]
@raivolink  Thanks for your response. 
Is there a way to do parallel execution on tests in same machine?

**Comment by raivolink** [comment]
This is not related to rpaframework issues. Please use community channels and documentation for general questions
