### ISSUE TITLE
Excel.Files Create Worksheet does not accept parm header=

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#121]
Although the documentation specifies parm header= for Create Worksheet it is not accepted in RIDE (I also specified content=).

Using
rpaframework                       7.0.5
rpaframework-core                  5.2.0
and RIDE 1.7.4.2

**Comment by osrjv** [comment]
Hi, thanks for the report. It's actually an issue with documentation being released too early. The argument was recently added and was merged to master, but hasn't been released to PyPI yet. We will try to push out the release still during this year.

I'll keep this issue open for the documentation part.

**Comment by Harm10** [comment]
I reran my test on rpaframework 9.3.4 and the problem is gone? So this issue can be closed?

**Comment by osrjv** [comment]
Yes, the original issue itself was that rpaframework.org was out of sync with releases in PyPI, which hasn't been fixed. But I can close this and re-open it as a separate issue to make that more clear.
