### ISSUE TITLE
Calling the wait_for_element function causing it hangs for the duration of the timeout

### ISSUE THREAD

**Issue by AntonStange** [robocorp/rpaframework#123]
https://github.com/robocorp/rpaframework/blob/f4bf8c782a7a2c34477d1e251edca9c81748c1af/packages/main/src/RPA/Desktop/Windows.py#L1145

Currently if there is one element matching the locator, and most cases this is true because a locator should be unique, we stay within the while loop / there's no break. 

Proposed code change is instead of larger than 1 use larger or equal to 1
if len(elements) **>=** 1:

**Comment by mikahanninen** [comment]
Thank you for the suggestion @AntonStange 👍 We will change this in the next release containing Windows library fixes.
