### ISSUE TITLE
html_body=True does not work in "Send Message" RPA.Outlook.Application

### ISSUE THREAD

**Issue by tjayadeera** [robocorp/rpaframework#133]
![image](https://user-images.githubusercontent.com/72373508/105814231-129fc500-5fd7-11eb-982c-330f1caf8d77.png)

Can not resolve html body using "html_body=True". 
Email's body returns -1 as the body.

**Comment by mikahanninen** [comment]
Thank you for the report 👍 Will be fixed in 7.4.1 release.

**Comment by mikahanninen** [comment]
Fixed with release 7.4.1
