### ISSUE TITLE
double click

### ISSUE THREAD

**Issue by marcelocecin** [robocorp/rpaframework#136]
hi there
please share an example of how to use double click in python
thank you

**Comment by osrjv** [comment]
For questions about how to use libraries, please post in either on Robocorp [forums](https://forum.robocorp.com/) or Slack. This issue tracker is for bugs and feature requests.

Here's one example though:

If you are talking the library `RPA.Desktop`, the [keyword documentation](https://rpaframework.org/libraries/desktop/index.html) lists the possible click actions (click, left click, right click, etc.), and those actions are accepted in all mouse-related keywords that have an action argument. Note, the action is case-insensitive; `double click`, `Double click`, `double_click` all work.

Also, all RF keywords listed in https://rpaframework.org/ are also callable directly as Python methods. For instance if you had the following RF script that uses `RPA.Desktop:`
```
*** Settings ***
Library   RPA.Desktop

*** Tasks ***
Type text into application
    Open application    client.exe
    Click    create.png    double click
    Type text     Some text in text field
```
It could be converted to Python:
```
from RPA.Desktop import Desktop

d = Desktop()
d.open_application("client.exe")
d.click("create", "double click")
d.type_text("Some text in text field")
```
