### ISSUE TITLE
Unable to install: Init Error: Failed to build Jupyter Lab.

### ISSUE THREAD

**Issue by Dranaxel** [robocorp/rpaframework#140]
Hello,

I'm using Windows 10, I have installed python 3.9 the used pip to install roboframework/robocore/Jupyter
But I always get the following message: "Init Error: Failed to build Jupyter Lab."
Does anyone got a workaround ? Thanks.

**Comment by osrjv** [comment]
Jupyter Lab should output logs with more verbose build errors (usually in a separate file), which will help you track down the issue. I however don't see how this is related to rpaframework and not the Jupyter project.

**Comment by osrjv** [comment]
However feel free to re-open if there is an error that points towards rpaframework being the issue in building Jupyter Lab. I also recommend trying out Robocorp Lab which will handle installing all of those for you automatically: https://robocorp.com/get-started

**Comment by Dranaxel** [comment]
Hi Ossi, Unfortunately i'm actually trying to install robocorp lab which is giving me the error. Would you prefer I send the logs here or I open a new issue ?

**Comment by osrjv** [comment]
Ah, ok. This still really isn't the best place for Lab issues.

When the error happens it should show an error dialog with the option to send an issue report with logs to Robocorp support. If you submit that issue, you'll get the fastest/best response.

If the submit issue dialog doesn't show up again, you can mail support@robocorp.com directly with logs (https://robocorp.com/docs/developer-tools/robocorp-lab/installation#robocorp-lab-log-file-locations).
