### ISSUE TITLE
Excel: Apply cell formatting to values

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#145]
I am testing Excel.Files and am living in Europe. Excel/Windows use comma to display the decimal point in Europe.
When I read the worksheet values are returned with a decimal point instead of the comma which is normal over here.
Is there a way I can set this Local setting within RPA? Or maybe in RIDE or Robot Framework? Or Python perhaps?

Also I notice that the formatting of the cell is not there. For instance if I set a cell to be an integer with 3 decimal digits and enter 1234,5 only in the cell, Excel shows the result as 1234,500 but reading the worksheet gives me just 1234.5
Is there a way I can use the formatting as well?

**Comment by osrjv** [comment]
Hi,

When the library reads values from worksheets it uses cell formatting to convert them into correct Python types instead of keeping everything as text. In this case, the numbers are converted into floats, which from Python's point of view is just a number without any concept of localization/formatting.

Usually, this is wanted because you might do maths on number fields and manipulate dates in a sane way. Do you have a situation where it would make more sense to keep everything as text so it would end up with the exact same formatting in a target system? Keeping the formatting but also allowing normal number operations for floats would be a bigger undertaking.

**Comment by Harm10** [comment]
I understand your reasoning. But I am creating csv files to upload to our mainframe which also uses comma as the decimal point indicator. So if you could add an option to not convert into Python format? Something like asis=yes?
Or is there something I missed in Python to do the conversion back for you?

**Comment by osrjv** [comment]
Ah, alright! I think the best way to handle this is to make sure your CSV writer creates data that is compatible with your mainframe. In the future it's possible that you get data with Python floats from some other source or an Excel file is formatted with a different localization, which would then break your robot in an unexpected way.

Are you using the CSV keywords in Tables or some other external library? If you have an example of the mainframe CSV format I could look into adding support for it directly in our libraries

**Comment by Harm10** [comment]
I am not sure I understand correctly. If I would use my CSV writer that would be Excel or software similar?
I need to get these files in csv format without that software being installed. I would like Excel.Files to give me just what is in the cells. Even better formatted like Excel (or similar software) has defined it (e.g. the amount of digits behind the comma) and even more better interpret any formula that is there. But getting the first would already help a lot! Is that possible?

I cannot just load the CSV data into the DB2 tables. They are processed (and checked on specific rules) by several Cobol programs first on the mainframe. Also the data gets sorted before it gets loaded.

Is that what you meant?

**Comment by osrjv** [comment]
Hmm, I might have misunderstood what the process is. You said that you are "creating CSV files to upload", which I assumed means that you are first reading Excel files into Python/RF and then writing the content into a new file in CSV format, which is then uploaded somewhere. Whatever the case, the part which does the writing to the mainframe should take care of the data being in the correct format, in my opinion.

Regarding cell formatting in Excel, it seems I didn't remember correctly. The float value for number fields _is_ the value that is stored in an Excel file. The (separate) cell formatting is applied to that value by Excel and displayed in a different way, and that includes the decimal separator. Unfortunately, I didn't find a ready-made Python implementation for parsing the formatting and applying it to values. It can be done, but it's a bunch more work than I expected.

**Comment by Harm10** [comment]
Thanks for your elaborate answer. At first I was glad that you said RPA did a conversion to Python format but was a bit weary about it being really true. It sounds more logical that Excel applies the formatting even the decimal comma.

I also did a search on GitHub and until now no package offers formatting (alas).

Maybe I should investigate Excel replacements to use. But again thanks for your investigations!

**Comment by osrjv** [comment]
Just to elaborate on my point about writing CSV (even if not related to this issue). If you read an Excel file like this with rpaframework:
```
from RPA.Excel.Files import Files

files = Files()
files.open_workbook("example.xlsx")
table = files.read_worksheet_as_table()
```
You end up with a python object like this:
```
print(table)
# Table(columns=['Index', 'Data', 'Id'], rows=10)
print(table[0])
# [1, datetime.datetime(2017, 10, 15, 0, 0), 1562]
```
Which you can then write to CSV:
```
from RPA.Tables import Tables
tables = Tables()
tables.write_table_to_csv(table, "output.csv")
```
That looks like this:
```
Index,Date,Id
1,2017-10-15 00:00:00,1562
2,2016-08-16 00:00:00,1582
3,2015-05-21 00:00:00,2587
4,2017-10-15 00:00:00,3549
5,2016-08-16 00:00:00,2468
...
```
If the mainframe you are dealing with has a specific format for that final CSV file, then we can add support for it in our Tables library and you can keep using Excel (or whatever else your data source is).

**Comment by Harm10** [comment]
I was trying your code in RIDE (2.0b1) on Python 3.7.9 but importing RPA.Tables gives me an error: FAILED RPA.Tables list index out of range
I have upgraded RPA framework to 7.6.0 (core 5.3.1) but the error remains.
According to the documentation there are no additional steps to activate RPA.Tables?

**Comment by osrjv** [comment]
It should not do any indexing on import, but please make a post on our forum (https://forum.robocorp.com/) or developer slack (https://robocorp-developers.slack.com/) as to not pollute this issue any further.

**Comment by Harm10** [comment]
Created a topic on the forum (still under moderation). For now I cannot check the result of write_table_to_csv in RIDE.
Will try to run the code in Python itself.

**Comment by Harm10** [comment]
I have tested your code directly in python and the csv gets created. But I do not see options to use Local settings or other options (I expected something like decpoint=comma or csvseparator=; which are normal in Europe). Could such options be added?

BTW the anchor links on https://rpaframework.org/libraries/tables/index.html do not work (they point to libdoc sub folder while the url specifies libraries)

**Comment by osrjv** [comment]
Currently it has the option for giving a "dialect", which defines all of those values at once. The supported options now being excel, excel-tab, and unix, which are the Python defaults. What I was suggesting is that we either add a whole new dialect if the format you need is a common one, and/or I expose all of those options individually.  Decimal point isn't part of that dialect currently, but can (most likely) be added at the same time.

And yes, that's on the todo list... the libdocs are currently in an iframe that prevents the anchors from working. Might try to tackle it when we switch to improved libdoc in RF4.

**Comment by Harm10** [comment]
That would be a great idea! Something like dialect=excel-europe ?
I tried to run your example in RIDE now I have more an idea on the syntax and it also runs! (The syntax option is still not working) 

And suppose my Excel file has it's own header (or headers) this is not discernible (and hence skippable) when using Excel Files?

**Comment by Harm10** [comment]
Any progress on this one?

**Comment by cmin764** [comment]
@Harm10
- With [Read Worksheet As Table](https://robocorp.com/docs/libraries/rpa-framework/rpa-excel-files/keywords#read-worksheet-as-table) you have the `header` option now, which if enabled it interprets the first row in the Excel file as a header defining the columns for the upcoming table below. (use it along with `start` in case it doesn't start from the first row)
- Similarly, [Read table from CSV](https://robocorp.com/docs/libraries/rpa-framework/rpa-tables/keywords#read-table-from-csv) & [Write table to CSV](https://robocorp.com/docs/libraries/rpa-framework/rpa-tables/keywords#write-table-to-csv) has a `header` switch as well.

----

Many improvements happened meanwhile and is a high chance that the latest `rpaframework==15.6.1` will be self-sufficient for fixing this. If there's a general need for a specific dialect, we may allocate time for it.

Reference [forum](https://forum.robocorp.com/t/failed-rpa-tables-list-index-out-of-range/532/13)
