### ISSUE TITLE
Word.Application AttributeError: object has no attribute 'SaveAs2'

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#146]
Testing the example as described on the documentation page.
I get this error on Save document AS:
AttributeError: '<win32com.gen_py.Microsoft Word 12.0 Object Library._Document instance at 0x1843598957768>' object has no attribute 'SaveAs2'

I should add that I have a non-English Word (Dutch) so maybe that is why SaveAs2 is not there?

**Comment by osrjv** [comment]
Hi,

According to Microsoft's documentation the SaveAs2 method was added in Office 2010. It looks like we will have to check the app version and use the old SaveAs method if needed.

**Comment by Harm10** [comment]
You probably already guessed it but I am testing on an older version: Office 2007. I know it's old but it still does what it needs to do! :-)

**Comment by osrjv** [comment]
Should be fixed in release 8.0.0, please re-open if it still happens

**Comment by Harm10** [comment]
Will test and report back.

**Comment by Harm10** [comment]
Problem is indeed solved! Thanks!
