### ISSUE TITLE
[RPA.Email.ImapSmtp] "Send message" - attachments containing language specific characters does not work

### ISSUE THREAD

**Issue by GSymonow** [robocorp/rpaframework#148]
Hello,
I'm trying to use "Send message" to send an email containing attachment with language specific characters like:
"chinese_华语言教学出版社.docx".

The email is sent but the attachments name is changed to "noname" without file extension. The content of the file is OK but it is renamed.

I was trying to use UFT-8 encoding:
${bytes} =  Encode String To Bytes	${strAttachment}  UTF8  errors=ignore
${strAttachmentUtf} =  Decode Bytes To String	${bytes}  UTF-8  errors=replace

Still it doesn't help.
Any help will be appreciated.
Best regards,
Greg

**Comment by mikahanninen** [comment]
Thank you for the report 👍  We will look into this.

**Comment by mikahanninen** [comment]
@GSymonow it was really silly bug in the library code, which probably should have failed way sooner than this. The attachment header was set incorrectly. I could replicate the problem and I was able to fix it. We will release the fix in the next release.

**Comment by GSymonow** [comment]
Thanks a lot.

**Comment by osrjv** [comment]
Fixed in release `8.0.0`
