### ISSUE TITLE
rpaframework 8.2.0 downgrades robotframework to 3.2.2

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#151]
I tried upgrading robotframework to 4.0 and failed because of rpaframework version rules.
So I uninstalled all rpaframework packages, upgraded robotframework to 4.0 and installed rpaframework again.
To my astonishment it directly downgraded roboframework to 3.2.2 without even asking for permission!
Even so I want to use robotframework 4.0. So how to resolve this situation?

**Comment by osrjv** [comment]
The currently released rpaframework versions define a dependency on Robot Framework 3.* and pip will happily overwrite previous packages if you use it to install new ones (and that's a feature of pip). The reason for that dependency being that we use various features from RF and it was known beforehand that the next RF version will not be backward compatible.

The necessary changes for RF4 and bumping the dependency have been merged to our master, but haven't been released yet. We'll try to get it out early next week.

Originally closed as issue #105.
