### ISSUE TITLE
RPA.Desktop.Windows activation changes look and feel of RIDE (e.g. font size)

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#152]
As soon as I activate library RPA.Desktop.Windows in RIDE the look and feel of the RIDE window changes.
The total screen becomes smaller and the font looks to be changed (also smaller?).
The pull down menu at the top is misaligned and hard to handle.
Everything is still working but this is quite annoying. There are no messages in the log.
RIDE version is 2.0b1, Python 3.7.9 and RPA 8.2.0

Deactivating the library does not revert this change. I need to restart RIDE to get the normal display.

**Comment by osrjv** [comment]
Sounds like RIDE runs everything in the same python process (the GUI itself, and the RF code it is executing), which is a bit questionable.

We're not explicitly doing anything to mess with GUI themes or such, but apparently, it's a side-effect of _something_. I can try to narrow it down to something more exact, but it's another question how much we can fix it (without removing features). Let's see if it should be here or RIDE issue tracker again.

**Comment by Harm10** [comment]
Any update on this one?

**Comment by mikahanninen** [comment]
@Harm10 I will close this issue due to inactivity. Hope you have been able to resolve the issue. The `RPA.Desktop.Windows` is a deprecated library in favor of `RPA.Windows`.

**Comment by Harm10** [comment]
@mikahanninen I missed your reply but also did not get any updates on my problem. I will retry with my current set-up and report back.
