### ISSUE TITLE
Dialogs File Input extended with option to not/approve overwrite existing file?

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#153]
I have an enhancement request for Dialogs:
Would it be possible to have some option with Add File Input that either can be set to not overwrite existing files in the target directory and/or that the user has to approve an overwrite of an existing file?

**Comment by osrjv** [comment]
A flag for failing on overwrite is easy to add, and a confirmation dialog should be possible too, I think. I'll add it to the roadmap.

**Comment by Harm10** [comment]
As the new version is there, any news on this one?

**Comment by tonnitommi** [comment]
RPA.Dialogs is replaced with RPA.Assistant that brings much more functionality, inc file inputs.
