### ISSUE TITLE
RPA.Cloud.AWS: Create Bucket: Add automatic or manual support for location constraints

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#163]
`9.4.0`: When using a region other than `us-east-1`, `Create Bucket` throws `IllegalLocationConstraintException`:

```
An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

The following issue suggests passing in location constraints when calling bucket creation:

https://github.com/aws/aws-cli/issues/2603

Is this something the library could handle automatically, or at least provide a way to pass the constraints?

**Comment by mikahanninen** [comment]
The `LocationConstraint` can be now set via `**kwargs` for the `Create Bucket` keyword.
