### ISSUE TITLE
Save JSON to file keyword should have also indent as optional argument

### ISSUE THREAD

**Issue by adrian-evo** [robocorp/rpaframework#164]
Currently it is not possible to specify indent argument to this keyword and as a consequence, if I read a json file, update a value and write back the file, the indent is missing and thus json is not easily readable anymore:

env.json - before
```
{
    "KEY": "value",
    "ANOTHER_KEY": "222"
}

```

&{env}  Load JSON From File    devdata/env.json
${new_env}    Update Value To JSON    ${env}    'KEY'    "value"
Save JSON To File    ${new_env}    devdata/env.json

env.json - after
`{"KEY": "value","ANOTHER_KEY": "222"}
`

Workaround:
Copy JSON.py as JSON2.py under project directory, rename class and modify the keyword. Obviously it is not so nice to move around JSON2.py instead of having the option by default.

```
        with open(filename, "w") as outfile:
            json.dump(doc, outfile, indent=4)

```

**Comment by mikahanninen** [comment]
@adrian-evo Good point. We will add that option `Save JSON to File` keyword

**Comment by mikahanninen** [comment]
Support added in 9.5.0

**Comment by adrian-evo** [comment]
@mikahanninen Thanks. I am waiting for RF 4.0.1 which fix https://github.com/robotframework/robotframework/issues/3919 then I can remove my custom JSON and use this one.
