### ISSUE TITLE
Add to "Filter Table By Column" operator "not contains"

### ISSUE THREAD

**Issue by IlfirinPL** [robocorp/rpaframework#165]
In some cases its useful to keyword [Filter Table By Column](https://rpaframework.org/libdoc/RPA_Tables.html#Filter%20Table%20By%20Column) add operator "not contains" to exclude results that contains pattern 

ex. use
| RPA.Tables.Filter Table By Column | ${list of file}  | name | not contains | done |

**Comment by osrjv** [comment]
I don't see why not, also "in" operator probably needs a negation.

**Comment by osrjv** [comment]
Closed in #168. Will be in the next release.
