### ISSUE TITLE
RPA.FileSystem: List Files In Directory: path argument documentation

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#170]
`RPA.FileSystem`: `List Files In Directory`:

`path` argument documentation says "defaults to current working dir":

> path: | base directory for search, defaults to current working dir

If the `path` argument is not given, this throws `TypeError: expected str, bytes or os.PathLike object, not NoneType`.

Expected behavior: Uses current working dir if no path is given OR update docs.

**Comment by osrjv** [comment]
This was fixed in release `9.6.0`
