### ISSUE TITLE
RPA.Word.Application open file in readonly mode

### ISSUE THREAD

**Issue by gmayu** [robocorp/rpaframework#171]
The 'Open File' keyword in https://rpaframework.org/libraries/word_application/index.html always open the word file in read only mode. So the keyword Save Document is not usable. You have to use Save Document As

**Comment by osrjv** [comment]
An extra argument for controlling `read_only` when opening files was added in `9.6.0`. I didn't change the default behaviour since it would've been backwards incompatible.
