### ISSUE TITLE
RPA.Browser.Selenium automatically remove readonly attribute

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#174]
Automatically remove readonly attribute from elements in relevant keywords. e.g.
``` 
Execute Javascript  document.getElementById("from_date").removeAttribute("readonly")
Input Text  from_date  08-Apr-2021`
```
This improvement idea is FOR CONSIDERATION.

**Comment by cmin764** [comment]
Since this is so old and I have never seen to be blocking any customer (yet), I'll close it. We can reopen if that's really a problem and the desired default effect.
