### ISSUE TITLE
RPA.Dialogs.Add Radio Buttons: Example code does not match the arguments

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#177]
[RPA.Dialogs.Add Radio Buttons](https://rpaframework.org/libdoc/RPA_Dialogs.html#Add%20Radio%20Buttons): Example code does not match the arguments.

```
element_id
options
default
```

```robot
Add Radio Button   element_id=drone  buttons=Jim,Robert  default=Robert
```

**Comment by osrjv** [comment]
I labeled this as a bug, but it might not make it into a release before we introduce the next iteration on Dialogs, which has larger impacting changes.

**Comment by osrjv** [comment]
The documentation was re-written for release `10.0.0`
