### ISSUE TITLE
RPAframework 10.0.2 dependency RPAframework-pdf < 0.6.0?

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#181]
If I update RPAframework-pdf I get this error:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rpaframework 10.0.2 requires rpaframework-pdf<0.6.0,>=0.5.0, but you have rpaframework-pdf 0.6.0 which is incompatible.`

Are the dependencies of your own packages not in good order?

**Comment by mikahanninen** [comment]
Thank you for the report. I will update pdf dependency version in the rpaframework package.

Are you running pip install commands manually or did you get that error via rcc (and conda.yaml) ?

**Comment by Harm10** [comment]
I am running pip install manually on Windows 10. 
When I reverted rpaframework-pdf I got a similar error (did not write it down) for chardet 4.0.0 on rpaframework itself.
So I reverted rpaframework to 10.0.1 as well (which took chardet to 3.0.4).

**Comment by mikahanninen** [comment]
There is now rpaframework 10.0.3 which includes rpaframework-pdf 0.6.0 (so you don't need to install it separately, just rpaframework). I will look into that chardet dependency.

**Comment by Harm10** [comment]
I installed 10.0.3 and the pdf got upgraded too to 0.6.0
So thanks!

Chardet remained at 3.0.4. The latest version of that is 4.0.0 which is outside the allowed version of 10.0.3
