### ISSUE TITLE
Update terminology in RPA.Robocloud.Secrets documentation

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#190]
[RPA.Robocloud.Secrets documentation](https://rpaframework.org/libraries/robocloud_secrets/index.html) uses old terminology ("Robocloud Vault", "Robocloud Worker", "Robocode CLI", multiple "Robocloud" mentions).

**Comment by osrjv** [comment]
Not only documentation, but the library is still named incorrectly. The migration should probably start asap with deprecation warnings, and an alternative import, i.e. `Robocorp.Vault`
