### ISSUE TITLE
Cannot upgrade robotframework-* packages due to limitation rpaframework 10.4.0

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#196]
I cannot upgrade robotframework-pythonlibcore and robotframework-requests due to the limitation set in rpaframework 10.4.0.
Please resolve.

**Comment by janipalsamaki** [comment]
Hi, @Harm10! Does the latest `10.9.0` resolve this issue? Both `robotframework-pythonlibcore` and `robotframework-requests` have been updated there.

**Comment by Harm10** [comment]
Upgrading to 10.9.x resolved the problem! Thanks for replying.
