### ISSUE TITLE
Type Text [Into] change characters

### ISSUE THREAD

**Issue by vx-i** [robocorp/rpaframework#199]
Hi all,

I have a strange behavior with 'Type Text Into'. It reverts semicolon into ü character. Any idea why?

I've also tried with 'Convert To String' but the same issue.

Many thanks in advance.

Platform: Windows 10
Framework: 10.6.0

**Comment by osrjv** [comment]
I'm sorry for the late reply. This sounds like an issue with the keyboard emulation.

Just to rule something out, can you open a command prompt and input the command `chcp` and report back the result?

**Comment by vx-i** [comment]
Hi, no problem. The output is

Active code page: 850

**Comment by vx-i** [comment]
@osrjv Many thanks for the hint. I followed this manual:
https://robocorp.com/docs/troubleshooting/windows-codepage

Now I get this result in CMD / PWSH:
Active code page: 65001

But command "Type Text Into" expects now that my keyboard layout is EN. Actually it is set to DE.

**Comment by osrjv** [comment]
Yes, it's still some sort of bug, possibly in the upstream pynput library. The keyboard input _should_ work independent of layout or code page.

I'll try to get a repro on my Windows machine and see if it's easily fixable.

**Comment by vx-i** [comment]
@osrjv Any updates on this topic from upstream?

**Comment by osrjv** [comment]
@vx-i, I did a bunch of poking around and there was nothing conclusive. One thing that I encountered is that WIndows Terminal reports back the wrong keyboard layout, or rather doesn't change it correctly: https://github.com/microsoft/terminal/issues/83

I decided to fork the upstream library and implemented a change that RPA.Desktop will always write text as unicode, which seems to circumvent the keyboard layout issues. The keyword `Press Keys` will have to use the old style for shortcuts to work, but that's a less likely problem.

Changes are included in `11.2.1`. Please re-open if it still persists.
