### ISSUE TITLE
Connect To DB2 Database fail, there was a spelling mistake

### ISSUE THREAD

**Issue by xyp632** [robocorp/rpaframework#200]
1. python 3.8.5
2. robotframework 4.1
3. rpaframework 10.8.0
4. ibm-db 3.0.2

Run Task, then Debug Console:
OperationalError: ibm_db_dbi::OperationalError: Exception('[IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001\r SQLCODE=-30082')

Code Review , I found a spelling mistake:
https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Database.py [line:287]
`self.config.get("usernamme"),`

**Comment by mikahanninen** [comment]
Thank you for the report! We will fix this during this week's release!

**Comment by osrjv** [comment]
Should be fixed in version `10.9.0`
