### ISSUE TITLE
RPA.Excel Files IndexError: list index out of range when reading empty sheet in xls and header=true

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#203]
If I read an existing but empty worksheet with header=true in a xls file I get error IndexError: list index out of range.
If I leave out header=true reading is OK.
This error does not occur when reading an existing but empty worksheet in a xlsx file. In stead I get an empty list (which is what I expect)

Python 3.7.9
RF 4.1
rpaframework 10.9.2

**Comment by osrjv** [comment]
Was able to reproduce and fix. It was a bit wrong also with .xlsx when reading into a Table directly. Will be fixed in the next release.

**Comment by Harm10** [comment]
OK. Any idea when next release will be there?

**Comment by osrjv** [comment]
Released as `10.9.3`

**Comment by Harm10** [comment]
I can confirm that the problem is resolved with this new version. Thanks!
