### ISSUE TITLE
Documentation: Example for `Get Window List` could be simplified

### ISSUE THREAD

**Issue by emanlove** [robocorp/rpaframework#204]
The code Example for the `Get Window List` keyword under rpa.Desktop.Windows is, as shown here,

``` robotframework
@{windows}    Get Window List
FOR  ${window}  IN  @{windows}
    Log Many  ${window}
END
```

The use of the FOR loop with the use of Log Many might be a little confusing to some ("why loop and use log many?"). An alternative might be

``` robotframework
@{windows}    Get Window List
Log Many  @{windows}
```

or if one is trying to demonstrate how one could go through each window a different alternative would be to keep the FOR loop but change `Log Many` to simply `Log`

``` robotframework
@{windows}    Get Window List
FOR  ${window}  IN  @{windows}
    Log  ${window}
END
```

**Comment by osrjv** [comment]
Good point. We're planning on doing a larger docs clean-up and overhaul soon, and I'll fix this too.

**Comment by cmin764** [comment]
`RPA.Desktop.Windows` got deprecated in favor to `RPA.Windows`, so please use the new [library](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows) instead.
