### ISSUE TITLE
There is no active desktop required for moving mouse cursor

### ISSUE THREAD

**Issue by Andrew-risk** [robocorp/rpaframework#206]
I've run RPA on my laptop and installed "remote chrome desktop".
I have a error with RPA sometimes:  "There is no active desktop required for moving mouse cursor" although I don't use "remote chrome desktop". The Screen is always on and the RPA moves a mouse sometimes.

**Comment by osrjv** [comment]
Hi, thanks for the report.

Can you elaborate a bit:
- What OS are you using?
- What version of RPA Framework are you using?
- What library are you using specifically?
- What is the full error traceback and what keyword does it come from?
- Are you just moving the mouse locally and not through the remote desktop?

**Comment by Andrew-risk** [comment]
Hi, win10,
from RPA.Desktop.Windows import Windows
win.click_type(x=51, y=263)

Version:
robocorp-dialog                    0.2.2
robotframework                     4.1
robotframework-pythonlibcore       3.0.0
robotframework-requests            0.9.1
robotframework-sapguilibrary       1.1
robotframework-seleniumlibrary     5.1.3
robotframework-seleniumtestability 1.1.0
rpaframework                       10.8.0
rpaframework-core                  6.2.2
rpaframework-dialogs               0.3.1
rpaframework-pdf                   0.7.0

I got error "There is no active desktop required for moving mouse cursor!".
It's all information, because I am using block "try: exception:"

I am moving the mouse only localy.

пт, 20 авг. 2021 г. в 23:59, Ossi R. ***@***.***>:

**Comment by Andrew-risk** [comment]
вс, 22 авг. 2021 г. в 11:18, Skorinichi ***@***.***>:

**Comment by cmin764** [comment]
Closing this as it got very old and `RPA.Desktop.Windows` got deprecated in favor of `RPA.Windows`.

Please open a feature request if `RPA.Windows` isn't sufficient for automation in this case.
