### ISSUE TITLE
Incorrect sort order in RPA.Tables.Sort Table By Column (ascending = descending)?

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#209]
`rpaframework==11.1.0`

`RPA.Tables.Sort Table By Column`: The `ascending` argument seems to sort descending when set to `True`. The default is `False`. That should mean descending, right? If I set it to `True`, it sorts descending, and ascending if set to `False`, which is unexpected.

**Comment by osrjv** [comment]
Confirmed, tested, and fixed.

Commit 32b26da9667ed3edb116154c2707494a94bea7fb

**Comment by osrjv** [comment]
The fix was released as part of `11.1.1`
