### ISSUE TITLE
TypeError: take_screenshot() got an unexpected keyword argument 'region'

### ISSUE THREAD

**Issue by joergwork** [robocorp/rpaframework#211]
In ...RPA/Desktop/Windows.py:1632
instead of:

`path = Desktop().take_screenshot(path=path, region=region)`

it should be:

`path = Desktop().take_screenshot(path=path, locator=region)`

**Comment by osrjv** [comment]
Thanks for the report, and you're right. That's my mistake from deprecating the old keywords from `RPA.Images`.

Fixed in 410010d95dbffcbfdbc6af938fbff16b7f3d8489

**Comment by osrjv** [comment]
The fix was released as part of `11.1.1`
