### ISSUE TITLE
RPA.JSON example of get value from json not working

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#212]
I am using RPA.JSON get value from json. I have tested the example specified in the documentation:
`# Get the name value for the first person
&{people}=    Convert string to JSON   {"People": [{"Name": "Mark"}, {"Name": "Jane"}]}
${first}=     Get value from JSON      ${people}   $.People[0].name`
but the return value is None. What is wrong in the example?
Case sensitive makes no difference and changing it to (a more logical syntax in my view) $.People.Name[0] also makes no difference.

rpaframework version 10.9.3

**Comment by osrjv** [comment]
It does seem to be an issue with case sensitivity. There were some other mistakes in the examples as well that I fixed.

This is the correct syntax:
```
Get value from JSON     ${people}   $.People[0].Name
```
Here's a breakdown of that particular JSONPath:
`$` selects the root object
`.People` selects the attribute 'People' in that object
`[0]` selects the first item in 'People'
`.Name` selects the attribute 'Name' in that item
...which results in 'Mark'.

The expression `$.People.Name[0]` would mean that 'People' is an object with the attribute 'Name', and you would take the first letter of the name.

**Comment by Harm10** [comment]
Apparently I did not test it correctly when I tried Name before I created this issue. Now it is working like you described.
I would think that besides a correct example in the documentation this expression structure needs to be explained as well?

**Comment by osrjv** [comment]
The library documentation links to https://goessner.net/articles/JsonPath/, because JSONPath is a fairly common syntax. Maybe it could also include a small description inside the same doc too.
