### ISSUE TITLE
RPA.HTTP difficult to use

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#217]
e.g. POST request with headers and basic auth requires 4 lines of code and list and dict that are both a bit clumsy to handle with RF syntax:

```
    &{Headers}   Create Dictionary  Content-Type=application/json
    @{Auth}      Create List  me@example.com  some_secret
    Create Session    my_session    https://robocorp.zendesk.com
    ...               headers=${Headers}  auth=${Auth}  verify=${TRUE}
    Post Request    my_session  api/v2/some.json  data=some data
```

**Comment by orlof** [comment]
Another vote for improving HTTP library API. E.g. uploading files is too complicated as you typically must:

1. Get binary file
2. Create file dictionary
3. Create headers dictionary
4. Create session
5. Make post request

With simpler api the file loading and file dictionary could be integrated into POST request keyword.

**Comment by tonnitommi** [comment]
tackle through examples https://robocorp.com/docs/development-guide/http/http-examples
