### ISSUE TITLE
RPA.Dialogs -> Add image -> [WinError 206] [BUG]

### ISSUE THREAD

**Issue by emilszymecki** [robocorp/rpaframework#221]
Hi 
I have problem with kewords Add image on RPA.Dialogs library

I tested od two machines with Windows 10 env rpaframework==10.3.0 and rpaframework==11.1.2

I have [WinError 206] when i used Add image

Task(s) failed:

Task Minimal task failed with: FileNotFoundError: [WinError 206]

Add image   ${CURDIR}${/}sample.jpeg
Add image   ${/}sample.jpg
Add image   sample.png

Always its the same

**Comment by osrjv** [comment]
Thanks for the report! I forgot to label and respond to this issue, but I reproduced the bug and it was related to Windows and images above a certain size. The "FileNotFoundError" from Windows is misleading and it isn't actually related to the paths at all.

I created a fix and it was released in `11.2.0`.
