### ISSUE TITLE
RPA.Tables consider easier syntax to change cell values during table iteration

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#226]
Currently this is the way to do it:
```
    FOR    ${row}    IN RANGE    ${table.size}
        ${value}=  Get Table Cell  ${table}  ${row}  name
        ${new_value}=  Convert  ${value}
        Set Table Cell  ${table}  ${row}  name  ${new_value}
    END
```
However, most people intuitively try to do this with standard table iteration e.g.
```
    FOR    ${row}    IN    @{table}
        ${new_value}=  Convert  ${row}[Column Name]
        Set To Dictionary  ${row}  Column Name  ${new_value}
    END
```
This does not give any errors, but changes are not reflected to the original table.
I propose implementing some kind of `Set Column In Row` (replace `Set To Dictionary` in above).

**Comment by emanlove** [comment]
Is the goal of this feature to only change the cell "type" or is there a larger purpose? I am assuming it has a larger purpose. If this feature sole purpose was to convert the type of a whole column I prefer the `Map column values` proposed keyword in the [Slack discussion](https://robocorp-developers.slack.com/archives/CVBU007LN/p1631887429017000). The advantage of this is it converts all value in a column without the loop based upon the conversion keywords.

I may just have this ticket mixed up with another.

**Comment by cmin764** [comment]
Looks like this was handled by Ossi on #495. Please stand by for an upcoming library release with the fix.
