### ISSUE TITLE
`Normalize Path` fails due to Permissions

### ISSUE THREAD

**Issue by Noordsestern** [robocorp/rpaframework#23]
I dropped `OperatingSystem` Library and used `RPA.FileSystem` instead. Now I run in to an odd permission error when calling `Normalize Path`:

![grafik](https://user-images.githubusercontent.com/5188411/86236284-2054af80-bb9a-11ea-8cac-419be317345a.png)

I have no idea, why permission rights are required or what OperatingSystem does differently.

**Comment by osrjv** [comment]
Thanks for the bug report.

It seems that the functionality for `Normalize Path` is a bit unexpected here. In addition to normalizing it resolves to an absolute path, and for some reason that creates a permission error (is that a network drive?). I'll change the keyword to match the functionality of the built-in `OperatingSystem`.

**Comment by Noordsestern** [comment]
> is that a network drive?

Yes, it is a network drive.

**Comment by osrjv** [comment]
`Normalize Path` should now behave as expected. The previous functionality was moved to the keyword `Absolute Path`. These are available in rpaframework `2.1.0`.
