### ISSUE TITLE
RPA.PDF.Get Text From PDF trims spaces from content

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#235]
There should be an option to disable the trimming as the text can be tabular data that is formatted using spaces. Without the leading spaces it is impossible to deduct the position of the text.

**Comment by orlof** [comment]
...seems that also the spaces inside the text are normalized into single space

**Comment by mikahanninen** [comment]
Implemented with rpaframework-pdf release 0.9.0. To be included in the next main release.

**Comment by mikahanninen** [comment]
Fixed with rpaframework 11.3.0
