### ISSUE TITLE
RPA with Python

### ISSUE THREAD

**Issue by TuyenSD** [robocorp/rpaframework#238]

**Comment by mikahanninen** [comment]
Hi @TuyenSD . Our tooling supports building bots with Python in addition to Robot Framework syntax.

See more at our documentation, for example. https://robocorp.com/docs/development-guide/qa-and-best-practices/python-robots#tldr.

Our portal includes some Robots which have been either fully or partly implemented using Python https://robocorp.com/portal/search?q=python.

If you have more questions or details regarding this issue please ask us on our Developers Slack https://robocorp-developers.slack.com/
