### ISSUE TITLE
RPA.Tables: Read Table From CSV splits a single column header by the letter 'a'. 

### ISSUE THREAD

**Issue by sahokas** [robocorp/rpaframework#25]
RPA.Tables: Read Table From CSV splits a single column header by the letter 'a'.

For example `schema_name` becomes `['schem', '_n', 'me']`

**Comment by osrjv** [comment]
Did we have an example file where this happens? Well, whatever the case, I think the documentation for the CSV keywords needs some work, as the dialect parameters are not explained at all.

**Comment by sahokas** [comment]
Not reproducible with latest versions as of today -> closing

**Comment by osrjv** [comment]
Despite the issue being closed, there were some problems with overriding the automatic behaviour, and the arguments were not documented properly. These will be fixed in the next release.
