### ISSUE TITLE
Excel: Files: Explain or fix logic behind Create workbook and saving

### ISSUE THREAD

**Issue by alxndrdiaz** [robocorp/rpaframework#270]
Hello. 

I am trying to create an Excel workbook using the following code: 

`from RPA.Excel.Files import Files`
`file_path = 'output/excel.xlsx'`
`files = Files()`
`files.create_workbook(path=file_path, fmt='xlsx')`

And no file is created in file_path. Is there any specific format for file_path, such as Path(file_path) from pathlib  or what is the correct way to create the file? I was unable to find any examples in the [documentation](https://rpaframework.org/libraries/excel_files/python.html#RPA.Excel.Files.Files).  Thanks for your help.

**Comment by osrjv** [comment]
Hi,

The documentation for `Create workbook` needs some more explanation, but the keyword creates a workbook _in memory_, You need to call `Save workbook` for any changes to be actually written to disk.

This has created confusion before though, so it will at least need documentation updates, and we might consider saving automatically when that keyword is called.

**Comment by alxndrdiaz** [comment]
Thank you so much.

**Comment by osrjv** [comment]
I'm actually going to re-open this and make sure either one or both of the fixes I mentioned will be implemented

**Comment by cmin764** [comment]
Only one thing was implemented in front of the other, the docs specifications (sine you can provide the path during creation or during save, therefore not auto-saving this time):
<img width="719" alt="Screenshot_2022-07-08_at_17_49_07" src="https://user-images.githubusercontent.com/709053/178016570-7b862736-6323-4c3d-9203-a1f5ca60d242.png">
