### ISSUE TITLE
2. Additional `*** Tasks ***` appearing in the docs

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#280]
A solution would be to append `*** Tasks ***` only in `robotframework` code blocks. (and the dev should write the examples in such a way they'll begin with the tasks (and not explicitly adding the tasks header ofc))

Another saner solution is to just remove this auto-addition of the `*** Tasks ***` header.

<img width="727" alt="Screenshot_2021-11-04_at_16_25_36" src="https://user-images.githubusercontent.com/709053/140353528-7f3e77cf-0e41-4668-a8bf-9a8e0ac28321.png">

**Comment by cmin764** [comment]
<img width="1277" alt="Screenshot_2022-01-13_at_11_23_35" src="https://user-images.githubusercontent.com/709053/149302351-aee7cc73-d8c4-45ee-ae83-c871f8051b34.png">

**Comment by cmin764** [comment]
Place where the code should be altered: https://github.com/robocorp/documentation/blob/29dcef65613dba1578b3521cde72cbbea07c1d04/config/utils/libdocJson2Html/parser.js#L17

Quick solution: If the `*** Tasks ***` header is already present in the code-block, then don't add it, otherwise add it at the beginning as it is right now.

**Comment by tonnitommi** [comment]
This seems to be fixed. Closing until further issues arise. :)
