### ISSUE TITLE
PDF library outputs duplicates to XML in notebook

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#283]
Paste following code into Lab cell and run it twice with SHIFT+ENTER
First run produces correct XML, but second run produces the same XML twice into the voice.xml - even if you delete voice.xml between runs. 
```
*** Settings ***
Library  RPA.FileSystem
Library  RPA.PDF

*** Tasks ***
Testing
    Get text from PDF  voice.pdf
    ${xml}  Dump PDF as XML  voice.pdf
    create file  voice.xml  ${xml}  overwrite=TRUE
```

**Comment by cmin764** [comment]
Might be related to that context ensuring of a PDF file/content which might interfere with the currently running kernel compared to the Python process that exits in the `rcc run` and VSCode cases. Similar to the empty XML [issue](https://github.com/robocorp/rpaframework/issues/243#issue-1015068830) case (when not reading some text first).

**Comment by cmin764** [comment]
This is solved now with the upcoming [fix](https://github.com/robocorp/rpaframework/pull/288) ([loom](https://www.loom.com/share/18ec3266048d42daa96a2101944fec0f) recording)
