### ISSUE TITLE
Adding RETURNING to RPA.Database

### ISSUE THREAD

**Issue by antusystem** [robocorp/rpaframework#286]
Hi, it would be awesome if I could return something after I add a new row to a table with INSERT and RETURNING. Example:

`${response}=    Query    INSERT INTO mytable (mycolumn1, mycolumn2) VALUES ('myvalue1', 'myvalue2') RETURNING id`

I am aware that Insert ist not a 'returnable statement' ([link1](https://github.com/robocorp/rpaframework/blob/5ca25d88793c042748091a677cc73a956da31be2/packages/main/src/RPA/Database.py#L531), [link2](https://github.com/robocorp/rpaframework/blob/5ca25d88793c042748091a677cc73a956da31be2/packages/main/src/RPA/Database.py#L512)) in `rpaframework`, so that line does not return anything.

Though, I can make my way around to obtaining the id in several different forms, this would be the easier one. Thanks

**Comment by cmin764** [comment]
Yes, a `returning` flag that can be switch to `True` explicitly would do the job. On it this Monday!
