### ISSUE TITLE
Windows library quietly fails to attach to window

### ISSUE THREAD

**Issue by osrjv** [robocorp/rpaframework#29]
When automating applications with `RPA.Desktop.Windows`, it might give an errors such as: `AttributeError: 'NoneType' object has no attribute 'wait'`.

This seems to be a regression that happens when it fails to attach to a window. It should raise a proper error or fallback to a sane default (top window?) but instead continues normally. Other keywords do not check if the property is None and attempt to access the dialog, which results in the error message above.

Reported initially in Robocorp forum: https://forum.robocorp.com/t/windows-desktop-application-robot-tutorial/82/2

**Comment by mikahanninen** [comment]
Fix in release 2.2.0
