### ISSUE TITLE
Enhance ability to select specific elements when doing desktop or Windows application automation

### ISSUE THREAD

**Issue by emanlove** [robocorp/rpaframework#297]
## Problem
Problem: With the limited ways to select an element (name,class,type,id) and only one search criteria per element (i.e. I can't specificy both name and type) nor the ability to relate to other elements (like parent child with xpath or css selectors) the ability to distinguish elements is very limited.

## Examples

Here are some examples that show the problem

```robotframework
*** Settings ***
Library  RPA.Desktop.Windows

*** Tasks ***
Copy Data From Notepad to Excel
   Open executable   notepad.exe  Untitled - Notepad
   Menu Select    File->Open...

   # These do not work because there are many similar elements
   #Type Into   name:File name:  ${CURDIR}/README.md
   #Type Into   File name:  ${CURDIR}/README.md
   #Type Into   File name  ${CURDIR}/README.md

   # .. and trying again to find a locator
   #Type Into   File name:  ${CURDIR}/README.md
   #Type Into   id:DropDown  ${CURDIR}/README.md

   # Trying to list out locators and find a good locator I tried
   ${elements}=  Get Window Elements     # not sure tif this is getting the File Open dialog elements
   Log Many  @{elements}

Explore The WordPad Application
   [Tags]  runme
   Set Automation Speed  slow
   # Open WordPad
   Open From Search    WordPad    WordPad    wildcard=true

   # Try to click on Bulleted Lists
   Mouse Click  Lists
   # .. but get "ValueError: Could not find unique element for 'Lists'" error
   # There is both the button and the drop down menu both of which have the name "Lists"
   # I could select this windows element if I could specify both the name and type as they
   # combined appear unique in this instance.
   #
   # List out window elements in order to find a good locator
   ${elements}=  Get Window Elements
   Log Many  @{elements}
   # -------------------
   
   Mouse Click  Rich Text Window
   Send Keys  Item{VK_SPACE}#1{VK_RETURN}
   Send Keys  Item{VK_SPACE}#2{VK_RETURN}
   Send Keys  Item{VK_SPACE}#3{VK_RETURN}
   Send Keys  Item{VK_SPACE}#4{VK_RETURN}
```

## Questions
- Is there an xpath type language?
- What do other solutions (White, WinAppDriver, Selenium/Browser Libraries) use?
- If other application automation tools were to add this functionality, what would the syntax for them be? I would be interested, if possible, in coming up with syntax or notation that is similar or the same given the overall context of tool syntax allows for this.

## Other Solutions
What do other solutions (White, WinAppDriver, Selenium/Browser Libraries) use?

### WinAppDriver

WinAppDriver appears to use Appium

### Appium

Has find_felements_by_... methods
https://appium.io/docs/en/commands/element/find-elements/

Does not appear to have multiple indicators for single element nor relate to other elements nor start search from an element. It does appear to return a list of all mathcing elements which would allow one to say it is the Nth item in the list. But this would seems very fragile as the numbers change.

### Browser Library

Browser Library has the cascaded selector syntax [[See "Cascaded selector syntax" under "Finding Elements"](https://marketsquare.github.io/robotframework-browser/Browser.html#Finding%20elements)] which allows one to search off of the previous selector results.

### Cascading and Multiple Match Criterias
What about a syntax like Browser Libraries which allows for cascading, using `>>`, and additional criteria - an AND if you will, using `++`? For example, back to the Bulleted List issues above a selector like `name:Lists ++ type:UIA_SplitButtonControlTypeId` which would specify both the name and the type for the element. Using both cascading and additional criteria one might use a selector like `Paragraph >> name:Lists ++ type:UIA_SplitButtonControlTypeId`.

Issues: Does either the `>` or the `+` have meaning within any of these selectors? Or would simply having the slector parser look for first ` >> ` (that is `{space}>>{space}`) and then ` ++ ` be suffiecient to be able to parse cleanly?

### Virtual Keys

pywinauto uses virtual keys. It is unsure if uiautomation has a similar syntax/function and where the difference are.

## References

[pywinauto locators](https://pywinauto.readthedocs.io/en/latest/HowTo.html#how-to-specify-a-control-on-a-dialog)

### Related Projects
[Python UIAutomation For Windows by Yin Kaisheng](https://github.com/yinkaisheng/Python-UIAutomation-for-Windows)

**Comment by mikahanninen** [comment]
As a short answer now - the new Windows library will have support for multiple criteria and cascading locators.

Some examples
```
id:clearButton
type:Group and name:'Number pad' > type:Button and index:4
type:Group and name:'Number pad' > control:Button index:5 
id:Units1 > name:${unit}
class:Button offset:370,0
```

**Comment by emanlove** [comment]
That looks great. I think that covers most scenarios for determining elements uniquely. Kiitos!

**Comment by cmin764** [comment]
Closing this as it got solved by the `rpaframework-windows` library. Please re-open if that's not the case.
