### ISSUE TITLE
Add possibility to RPA.Desktop.Windows library to send keys "as is"

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#301]
example custom keyword

the obvious use case is when sending keys to the password field

```python
    def send_raw_keys(self, keys):
        escaped_string = ""
        for k in keys:
            escaped_string += k if k.isalnum() else "{%s}" % k
        self.send_keys(escaped_string)
```

**Comment by cmin764** [comment]
Since `RPA.Desktop.Windows` got deprecated in favor to `RPA.Windows`, I guess that the new [library](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows) can be used instead and this Issue discarded.
