### ISSUE TITLE
Could we unify version number of rpaframework and all it's "sub"-packages

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#311]
Currently it is difficult to know what version of rpaframework sub-packages should be installed. Could we unify the versioning of all packages so that all rpaframework related packages would always get released simultaneously with same version number:

e.g.

```
  rpaframework==12.0.3
  rpaframework-google==12.0.3

```

**Comment by cmin764** [comment]
History showed us that this is not a viable option. That's why we have extras, so a `rpaframework[<extra>]==<ver>` pin will bring in the correct compatible version. (let's reopen if there's still something to be done here)
