### ISSUE TITLE
Robocloud.Items: provide access to full work item payload

### ISSUE THREAD

**Issue by sahokas** [robocorp/rpaframework#32]
Currently the `Robocloud.Items` library is built around the convention of Robocloud work item payload being a JSON object with another `variables` object containing key/value pairs. This is a simple and sensible convention for many use cases.

However, especially with integrations to external systems, the payload format cannot always be controlled. One such example is launching a process on Typeform subscription, as discussed here: [https://forum.robocorp.com/t/how-to-trigger-a-robot-from-typeform/100](https://forum.robocorp.com/t/how-to-trigger-a-robot-from-typeform/100). Robocloud itself does not have constraints for the schema of the payload (apart from size limit).

In addition to the opinionated structure with `variables`as key/value pairs, RPA framework could provide means to access the entire work item payload object.

**Comment by osrjv** [comment]
Two new keywords added: `Get work item payload` and `Set work item payload`. They are available in release `2.4.0`.
