### ISSUE TITLE
Add SFTP support to FTP library

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#333]
This can be implemented using FTP_TLS class from the ftplib.

Example below minus doc string, additional options and error handling.

```python
from RPA.FTP import FTP
from ftplib import FTP_TLS

class SFTP(FTP):

    def __init__(self, *args, **kwargs):
        FTP.__init__(self, *args, **kwargs)

    def connect_sftp(self, host:str, port:int, username:str, password:str, timeout:int=10):
        self.instance = FTP_TLS(timeout=timeout)
        self.instance.connect(host, port)
        self.instance.login(username, password)
```

**Comment by nduc** [comment]
Looking forward to this.
Thank you!

**Comment by nduc** [comment]
Any update on this?

**Comment by mikahanninen** [comment]
@nduc Sorry for LONG delays. The RPA.FTP is supporting TLS at the moment, but the SFTP support needs to implemented using different package and we will add that support shortly.
