### ISSUE TITLE
Adding BCC and CC to ImapSmtp Library

### ISSUE THREAD

**Issue by antusystem** [robocorp/rpaframework#338]
There should be a way to Send Messages with ImapSmtp Library with **_CC_** o _**BCC**_ (a.k.a. _**CCO**_), right now it is limited to send message with **_TO_**, but sometimes you want to send a copy to someone else and there is this limitation. 

My idea would be change the parameter _recipients_ to 3 new parameters: _CC_,  _BCC_ and _TO_, in which you would write the mails you want to send in each parameter

**Comment by mikahanninen** [comment]
@antusystem thank you for pointing out this missing feature in the library 👍

**Comment by tonnitommi** [comment]
BCC and CC are supported by both `RPA.Email.Exchange` and `RPA.Email.ImapSmtp`.
