### ISSUE TITLE
[Email.ImapSmtp] IMAP port is never used

### ISSUE THREAD

**Issue by Noordsestern** [robocorp/rpaframework#34]
Hi,

the imap port specified in `ImapSmtp` Library is never used. Imap connections always go against port `993`. 

I think, this line where the connection is created, is missing the port: https://github.com/robocorp/rpaframework/blob/e2ce2375ff0a0fccbb8c730e6d4ae2f922eb73e1/packages/main/src/RPA/Email/ImapSmtp.py#L193

Kind regards,
Markus

**Comment by osrjv** [comment]
I think you are correct. I'll fix this and include it in the next release.

**Comment by osrjv** [comment]
This is now available in PyPI, thanks for the report.
