### ISSUE TITLE
Windows library. Problem on locators using single quotes in locator values

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#363]
**rpaframework-windows == 2.0.1**

**How to replicate.**

Trying to use `Control Window` keyword on the application window, which has `'` character in the title. 
The window title is not matched correctly and keyword will fail after timeout

**Workaround**

Using locator strategy subname or regex to workaround  `'` character

**Comment by cmin764** [comment]
I confirm it, also not even the workarounds work with a simple Notepad title like: `file.txt - Notepad`.

- `subname:file.txt` works
- `subname:file.txt -` doesn't
