### ISSUE TITLE
Desktop Windows - Open Dialog - Update documentation or function

### ISSUE THREAD

**Issue by Mavnus04** [robocorp/rpaframework#364]
The Open Dialog keyword does not currently report a return value, however it appears there is a `return app_instance` at the end of the function.
Suggested to update documentation to include this return and update the examples for it.  All other 'Open *' keywords return the app instance id.

https://github.com/robocorp/rpaframework/blob/2a6a4abe56c7fece4f9cfed1ba488774393abdd8/packages/main/src/RPA/Desktop/Windows.py#L672-L728

**Comment by cmin764** [comment]
`RPA.Windows` is the new black now.
