### ISSUE TITLE
Desktop Windows - Add example for Find Element

### ISSUE THREAD

**Issue by Mavnus04** [robocorp/rpaframework#365]
Consider updating the documentation to include an example of using search_criteria.
Maybe also update the possible different search_criteria that is accepted.  Looks to be related to `WINDOWS_LOCATOR_STRATEGIES `

https://github.com/robocorp/rpaframework/blob/2a6a4abe56c7fece4f9cfed1ba488774393abdd8/packages/main/src/RPA/Desktop/Windows.py#L1296-L1311

**Comment by cmin764** [comment]
@Mavnus04 This `RPA.Desktop.Windows` library just got [deprecated](https://rpaframework.org/releasenotes.html#mar-2022) as of `rpaframework` **12.10.0** in favor to `RPA.Windows`. Will the new [Get Element](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows/keywords#get-element) keyword be sufficient for you in this case? (search for **Locators** [here](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows))

**Comment by cmin764** [comment]
I'm going to close this since is kinda old and we have an alternative presented [above](https://github.com/robocorp/rpaframework/issues/365#issuecomment-1077823454). If our current `Get Element` is not enough, we'll improve the docs/logic there.
