### ISSUE TITLE
RPA.Email.Exchange Wait for Message keyword throws an error

### ISSUE THREAD

**Issue by AllanMedeiros** [robocorp/rpaframework#377]
Hello everyone!
I'm using RPA.Email.Exchange to check emails and it's running on Docker container based on robotframework-browser image.
When the execution gets to Wait for Message keyword, it doesn't even waits and throws error **AttributeError: 'EWSTimeZone' object has no attribute 'localize'**.
I was getting invalid "\UTC" timezone error before, but then I have properly set the timezone using this command in the dockerfile:
`ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone`
![image](https://user-images.githubusercontent.com/34678196/152054117-7b7a5f82-4028-4e82-bea4-cee93bad15b0.png)

Other keywords like List Message and Send Message are working fine.
Any help is appreciated, thank you!

**Comment by AllanMedeiros** [comment]
Hi, just confirmed that the issue applies to Windows too.
Tested on Windows 10 Pro with last Nodejs, Robot Framework and Python 3.9.6.

**Comment by mikahanninen** [comment]
@AllanMedeiros  Problem with exception is that I have not been able to replicate it. I need to have **conda.yaml** defining the environment where this problem occurs.

`AttributeError: 'EWSTimeZone' object has no attribute 'localize'`

**Comment by mikahanninen** [comment]
I think I found the reason and there will be fix in the next release
