### ISSUE TITLE
RPA.Dialogs don't support ${\n} new lines in Add text

### ISSUE THREAD

**Issue by TimothyLopas** [robocorp/rpaframework#390]
Currently when creating dialog text using the "Add text" keyword you can either let the line auto-wrap or you can add multiple "Add text" keywords to break the lines where you want. The "Add text" keyword recognizing the ${\n} variable as a newline would also be a nice feature.

**Comment by tonnitommi** [comment]
RPA.Dialogs is replaced by RPA.Assistant. Will not fix.
