### ISSUE TITLE
Create output work items with files

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#392]
We want to conveniently create output work items containing files and/or variables and even save them in one go. For achieving this, the following improvements can be brought:
- [x] `files: Optional[Union[str, List[str]]]` param which accepts a string (or list of strings) for one/multiple files. (if string, can be also comma separated list of files -- the `name` of each file will be identical to the file name on disk (as if we run `Add Work Item File      path/to/file.ext` without any `name` parameter))
- [x] `variables: Optional[dict]` param which accepts a dictionary of variables. (can be created beforehand with `Create Dictionary`)
- [x] To remove the need of calling `Save Work Item` afterwards, a `save=False` keyword argument will do the job automatically if switched to `True`.

Example of keyword call:
_Insead of_
```robotframework
My Task
    Create Output Work Item
    Add Work Item File    output.xls
    Set Work Item Variables    user=John    mail=john@company.com
    Save Work Item
```
_Do_
```robotframework
My Task
    &{variables} =    Create Dictionary    user=John    mail=john@company.com
    Create Output Work Item    output.xls    variables=${variables}    save=${True}
```

**Comment by cmin764** [comment]
@tlaakso1 Is above accurate :)?

**Comment by tlaakso1** [comment]
> @tlaakso1 Is above accurate :)?

LGTM!
