### ISSUE TITLE
example code in Word.Application failure

### ISSUE THREAD

**Issue by yjheo15** [robocorp/rpaframework#40]
When I run the code in the example, I get the following error:

AttributeError: wdStory

May I know how to fix this?
Also, it would be nice if error messages would be more informative.

Thanks in advance!

**Comment by osrjv** [comment]
Hi, thanks for the report. It seems we were making some assumptions that weren't correct, and it should now hopefully be fixed in release `2.5.0`. In general we will try to improve the error messages from invalid user inputs, but in this case the error was internal and not from an expected place.
