### ISSUE TITLE
RPA.Excel.Files give cell color

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#413]
Would it be possible to add functionality to give a cell a color? This would be handy to identify cells that have incorrect value or just should stand out.

**Comment by Harm10** [comment]
Is this the right platform to ask for an enhancement?

**Comment by Harm10** [comment]
@mikahanninen Can you please inform me whether this enhancement request has been picked up?

**Comment by mikahanninen** [comment]
Sorry for not responding in a timely manner. This is the correct place to submit issues. Can't say when this would be added into **RPA framework** but if possible will be included in the next batch `RPA.Excel.Files` enhancements.
