### ISSUE TITLE
RPA.Windows. Improve keyword `Send Keys`

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#417]
In some cases the keyword `RPA.Windows.Send Keys` seems not to work as expected. Using different actions like pressing menu shortcut keys and writing text into input field produce sometimes unexpected behaviour. Some times as workaround `RPA.Desktop.Press Keys` works better for menu short cuts.

simple example
```robotframework
    Control Window    name:LibreOffice
    RPA.Desktop.Press Keys    alt    O     # opens "Open File" menu action
    RPA.Windows.Send Keys   keys={Alt}O     # does not work
    RPA.Windows.Send Keys   keys={Alt}(O)   # does not work
    RPA.Windows.Send Keys   desktop   keys={Alt}O    # does not work
```

**Comment by cmin764** [comment]
Actually the right key for it was `{LAlt}o` since the program is instructed to listen for left Alts + o.

![left-alt-o](https://user-images.githubusercontent.com/709053/162766741-84aa6d3c-72c5-47ab-bafb-936249107ecb.gif)
