### ISSUE TITLE
Pop Table Row: Unknown index name: Table(columns=['name', 'age'], rows=3)

### ISSUE THREAD

**Issue by jdnr** [robocorp/rpaframework#42]
I'm working with the following code:

@{lst_a}=             Create List    a    b    c
@{lst_b}=             Create List    1    2    3
&{dct_t}=             Create Dictionary    name=${lst_a}    age=${lst_b}
${table_t}=           Create Table    ${dct_t}
Log                   ${table_t.index[0]}
&{_}=                 Pop Table Row    table=${table_t}

Which results on:
ValueError: Unknown index name: Table(columns=['name', 'age'], rows=3)

This is raised by Table._location on line 337:
raise ValueError(f"Unknown {name} name: {value}")

The cause is rooted on an extra parameter when invoking get_row, on line 1021:
values = table.get_row(table, index, as_list)

It should be:
values = table.get_row(index, as_list)

Replacing "Pop Table Row" with this:
Set Column As Index   table=${table_t}    column=name

I get this other error:
TypeError: Keyword requires Table object

This is raised by Tables. requires_table on line 868:
raise TypeError("Keyword requires Table object")

The cause is rooted on a missing table parameter when invoking Tables.pop_table_column on line 1055:
values = self.pop_table_column(column)

It should be:
values = self.pop_table_column(table, column)

**Comment by osrjv** [comment]
Hi, thanks for the report and sorry about those issues.
I was planning on creating a release today, and I will include fixes for these in it (and improve test coverage accordingly)

**Comment by osrjv** [comment]
This should now be fixed in release `2.5.0`.

**Comment by jdnr** [comment]
Thank you Ossi.  
This is working now.
