### ISSUE TITLE
RPA.Database "Row Count Is Equal To X" raises exception "AttributeError: 'int' object has no attribute 'encode'"

### ISSUE THREAD

**Issue by jdnr** [robocorp/rpaframework#44]
<img width="797" alt="Screenshot 2020-08-18 at 10 19 34" src="https://user-images.githubusercontent.com/12010562/90497529-16354300-e13f-11ea-80e2-ea59aba197ac.png">

This is my configuration:

<img width="222" alt="Screenshot 2020-08-18 at 10 45 15" src="https://user-images.githubusercontent.com/12010562/90498216-ed617d80-e13f-11ea-9f4e-09de3022cd6e.png">

I updated it right after the release of rpaframework 2.5.1
I can work around the issue using keywords "Row Count" and "Should Be Equal As Integers" instead.

**Comment by mikahanninen** [comment]
Thank you for the report! We will fix this.

**Comment by mikahanninen** [comment]
We are extending `robotframework-databaselibrary` package, which unfortunately seems to be source of the problem you are facing. Luckily there is a workaround for you. 

As aforementioned package seems that is no longer under active development, we will implement needed keywords in our own library.

**Comment by mikahanninen** [comment]
Closing this issue now as `RPA.Database` has now new implementation.
