### ISSUE TITLE
RPA.Database Query return results in wrong format

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#443]
Information from support forum:

> Issue with RPA.Database library, keyword Query. The results returned from DB are not in the right format. All the values returned are placed in the first column and not distributed in the columns as they should be.

```
SELECT firstname, lastname, email FROM Users
[ {"firstname": ("my_firstname", "my_lastname", "my_email"), "lastname": None, "email": None ]
```

**Comment by orlof** [comment]
https://robocorp-developers.slack.com/archives/C010E91EBA6/p1648655905809399

**Comment by orlof** [comment]
I haven't been able to repeat the problem:
```
*** Settings ***
Library  RPA.Database
Library  RPA.FileSystem

*** Tasks ***
MMy Tasks
    Remove File    my-test.db
    Connect To Database  sqlite3  my-test.db
    Query  CREATE TABLE USER (id INTEGER, name TEXT)
    Query  INSERT INTO USER (ID, NAME) VALUES (1, 'aaaaa')
    Query  INSERT INTO USER (ID, NAME) VALUES (2, 'bbbbb')

    ${result}=  Query  SELECT * FROM USER
    FOR  ${row}  IN  @{result}
        Log  ${row}
    END
```
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1869202/161043040-1af95b80-d0fd-43dd-93aa-e8cd128f6cd6.png">

**Comment by orlof** [comment]
I asked for more information:

1. rpaframework version
2. database
3. code to repeat the problem

**Comment by lucielavickova-tesena** [comment]
Hello, here is the requested info:
**1. rpaframework version:**
rpaframework                       12.10.1
rpaframework-core                  6.6.2
rpaframework-dialogs               0.4.2
rpaframework-pdf                   1.30.4
rpaframework-windows               2.3.2

**2. database:**
Local Microsoft SQL Server DB, pyodbc driver

**3. code to repeat the problem:**
https://github.com/Tesena-smart-testing/robotfw-database-comparator/tree/rpaframework

**Comment by lucielavickova** [comment]
I published the example including the database backup on https://github.com/lucielavickova/rpadatabase-issue-443 
I hope this helps

**Comment by cmin764** [comment]
> Hello, here is the requested info: **1. rpaframework version:** rpaframework 12.10.1 rpaframework-core 6.6.2 rpaframework-dialogs 0.4.2 rpaframework-pdf 1.30.4 rpaframework-windows 2.3.2
> 
> **2. database:** Local Microsoft SQL Server DB, pyodbc driver
> 
> **3. code to repeat the problem:** https://github.com/Tesena-smart-testing/robotfw-database-comparator/tree/rpaframework

Hi @lucielavickova-tesena , as I'm debugging this, can you tell me if you're using SQL Server 2019, 2017 or other version? Also, what are the exact parameters you're connecting with to the DB and are you using the default configuration when connecting to? Thx!

**Comment by orlof** [comment]
@cmin764 Does it mean that pyodbc query returns data in different format than e.g. sqlite3? Is there some reasonable way to support both?

**Comment by cmin764** [comment]
> @cmin764 Does it mean that pyodbc query returns data in different format than e.g. sqlite3? Is there some reasonable way to support both?

Yes for both, `sqlite3` returns a list of tuples for the fetched rows, while `pyodbc` returns a list of `Row` objects which have to be normalised to tuples. I'll prepare a quickfix + some tests to make sure it works.

**Comment by cmin764** [comment]
@lucielavickova @lucielavickova-tesena you can upgrade now to `rpaframework==13.0.3` as the issue just got solved. See test [results](https://github.com/robocorp/rpaframework/pull/453#issuecomment-1088904356).
