### ISSUE TITLE
RPA.Email.ImapSmtp sending bcc does not send the email 

### ISSUE THREAD

**Issue by joseferrerh** [robocorp/rpaframework#447]
When including bcc in a Send Message keyword it does not send the email:

This works:
    Send Message  sender=sender@domain.com
    ...           recipients=${infoTrabajador}[E-mail profesional]
    ...           subject=${subject}
    ...           body=${EMAIL_BODY}
    ...           html=${TRUE}
    ...           attachments=${attachment}

This doesn't work:
    Send Message  sender=sender@domain.com
    ...           recipients=${infoTrabajador}[E-mail professional]
    ...           bcc=${bccEmail}
    ...           subject=${subject}
    ...           body=${EMAIL_BODY}
    ...           html=${TRUE}
    ...           attachments=${attachment}

Thanks

**Comment by mikahanninen** [comment]
Which rpaframework version ?

**Comment by joseferrerh** [comment]
Oh, sorry, yes
     rpaframework==13.0.0
Thanks

**Comment by mikahanninen** [comment]
Ok 👍 Seems that there is something wrong.

**Comment by mikahanninen** [comment]
And I guess you mean that bcc recipient does not get email ? The recipients should still receive the email...

**Comment by joseferrerh** [comment]
In my test, the recipients didn´t get the email.
