### ISSUE TITLE
Whether win32 is supported

### ISSUE THREAD

**Issue by wcccode** [robocorp/rpaframework#46]
https://github.com/robocorp/rpaframework/blob/9be57ff58a83ac490935694f3e3df38149dabfaa/packages/main/src/RPA/Desktop/Windows.py#L516

**Comment by mikahanninen** [comment]
Hi. Good point. I will add a keyword for switching backend and set all keywords setting backend to use that one.

**Comment by mikahanninen** [comment]
Supported backends are "uia" and "win32". This fix will be part of the next release. Thank you for reporting 👍

**Comment by mikahanninen** [comment]
released in 3.0.0
