### ISSUE TITLE
RPA.PDF - Ability to read binary content of pdf directly instead of providing source path of file

### ISSUE THREAD

**Issue by Shashank-Pathak** [robocorp/rpaframework#466]
I am trying to read pdf
```
from RPA.PDF import PDF
pdf = PDF()
pdf.open_pdf(pdf_binary_data)  # pdf_binary_data is content of pdf file
```
Is there any workaround to achieve this?
I already have pdf_binary_data available with me. Is there a way I can directly pass on data to pdf instance and perform operations on it.
Thanks

**Comment by cmin764** [comment]
While this will be very convenient indeed, we currently do not support that and it isn't trivial to add it in the game, as each parsed PDF document is mapped to a file path (`{<path/to/file.pdf>: <pdf_doc_obj>, ...}`), therefore we're working with paths, so you need to save first the binary data into an existing file on disk.
We're strict here just to avoid confusion when [Switch To Pdf](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#switch-to-pdf) on already parsed or new PDF files and when `Close[ All] PDF[s]` is issued. (and we don't want to mix file paths with streams/data here)

Can you please elaborate a little bit more your use-case on our [forum](https://forum.robocorp.com/) in case you really find it non-optimal or slow when redundantly saving files back to disk prior the reading?
