### ISSUE TITLE
RPA.JSON Delete from JSON cannot use Filter Expressions

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#481]
Filter expressions such as `$.People[?(@.Name=="Mark")]` (using the common example in the docs) used with the `Delete from JSON` keyword cause the `RPA.JSON` library to raise a `NotImplementedError` exception. From what I can see digging into the underlying `jsonpath-ng` this is because the `Filter` class does not implement the `filter` method. When `jsonpath-ng` is handling the `Child(Root(), Fields('People'))` on the left where the right is the `Filter([Expression(Child(This(), Fields('Name')) == 'Mark')])`, it attempts to call `filter` at the below lines from the `Child` class.

```python
    def filter(self, fn, data):
        for datum in self.left.find(data):
            self.right.filter(fn, datum.value)
        return data
```

I can identify the issue here, but I am not really sure how to change our implementation in `RPA.JSON` to avoid this issue.

**Comment by cmin764** [comment]
Also the unit-test for the delete functionality is missing.

**Comment by cmin764** [comment]
Other people found it to be [bugged](https://github.com/h2non/jsonpath-ng/issues/42) as well.
