### ISSUE TITLE
`RPA.Excel.Files` Contains Sphinx Formatting Errors

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#510]
The `Get Active Worksheet` keyword renders incorrectly:

![image](https://user-images.githubusercontent.com/93772257/169102390-76983c40-6580-4135-8b1f-8b52d870d71e.png)

I believe this may be caused because there is not a blank line between `.. code-block:: robotframework` and the first line of code in the example.

**Comment by mikahanninen** [comment]
Fixed RPA.Excel.Files formatting issues directly in the master branch.
