### ISSUE TITLE
for_each_input_work_item: Builtin.run_keyword does not take **kwargs

### ISSUE THREAD

**Issue by fabioz** [robocorp/rpaframework#517]
This came up while I was doing some testing:

In https://github.com/robocorp/rpaframework/blob/e6e70172baf26276e873ba14f5b9fdcb1e3cfc80/packages/main/src/RPA/Robocorp/WorkItems.py#L1634 it seems to be trying to pass `**kwargs` to `Builtin.run_keyword`.

Now, the `Builtin.run_keyword()` function does not take `**kwargs`... I guess it may still be in the signature in `for_each_input_work_item` for the pure-python case where a callable is received, but in the Robot Framework case this isn't valid.

Not sure the best approach here... usually if you have something that'd be a keyword arg and it doesn't match a keyword it'd still be matched in robot framework in the `*args` but the full arg would be considered a string.

-- i.e.: something as `For each input work item  |  Log  |  foo=bar` should log `foo=bar`, so, maybe convert the `kwargs` received to a string as received and add them to `*args`?

**Comment by cmin764** [comment]
Closing this in favour of creating a wrapper keyword which takes positional args only, keyword that can be passed to the for-each helper.

For anything else we let it break (with obvious message) if somebody passes keyword arguments to the called RF keyword.
