### ISSUE TITLE
`RPA.Dialogs` realtime field validators

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#530]
Ability to add input field validators which will dynamically check (as you type) and highlight wrong inputs.

### Problem scenario

Asking for a six-digit number like so:
```robotframework
Minimal task
    FOR    ${counter}    IN RANGE    100
        Add heading    Input a number
        Add text input    number
        ${result}=    Run dialog
        ${valid_partnumber}=    Run Keyword And Return Status    Should Match Regexp    ${result.number}    	^\\d{6}$
        Exit For Loop If  $valid_partnumber
        Add icon    Warning    size=64
        Add Heading    Number must be six digits
    END
```
will re-open the dialog until you get it right. What if only one field is bad and the rest are good? (you might need to refill or add more code to handle that) -- also it's annoying to find out what's the problem after you click the submit button

### Solution

A `validator` keyword argument supporting these types of validation:
1. Regex based (for textual inputs)
2. Function/Keyword based (with some default internal implementations available to use)

**Comment by tonnitommi** [comment]
`RPA.Dialogs` is replaced by `RPA.Assistant`, validation is in consideration in that library,
