### ISSUE TITLE
robocorp_dialog-0.5.3-py3-none-any.whl is detected by Zillya on virustotal.com

### ISSUE THREAD

**Issue by nizwiz** [robocorp/rpaframework#532]
Says Trojan.Disco.Win32.1337

**Comment by cmin764** [comment]
@bogdancondurache / @osrjv I guess that's due to the packed-in executable, right? :-s

**Comment by bogdancondurache** [comment]
@cmin764 yes, usually packaging executables will trigger some crazy heuristics in anti-viruses. At the same time if it is just Zillya (a smaller vendor) we can just send them a sample and ask them to ignore it from now on.

**Comment by bogdancondurache** [comment]
Issue solved, no longer detected as malware by Zillya
