### ISSUE TITLE
RPA.HTTP support for POST that contain files and data

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#533]
I was trying to convert the following python requests code to RPA.HTTP, but I was not able to combine streaming file upload with "form-data". It could be a missing feature in RPA.HTTP or just the lack of proper example.

```
import requests
from requests.auth import HTTPBasicAuth

def jobs(filename):
    with open(filename, "rb") as f:
        return requests.post(
            "https://sandbox.zamzar.com/v1/jobs", 
            data={"target_format": "txt"}, 
            files={"source_file": f}, 
            auth=HTTPBasicAuth("ADD_HERE_THE_BASIC_AUTH_STUFF", '')).json()
```

Here is a [link to API docs](https://developers.zamzar.com/docs#section-Starting_a_new_job_for_a_local_file)

**Comment by mikahanninen** [comment]
This example is from [Robot Framework Requests](https://github.com/MarketSquare/robotframework-requests/blob/master/atests/testcase.robot) tests. 

Have you tried something like this ?

```robotframework
Post Request With Data and File
    [Tags]    post
    &{data}=    Create Dictionary    name=mallikarjunarao    surname=kosuri
    Create File    foobar.txt    content=foobar
    ${file_data}=    Get File    foobar.txt
    &{files}=    Create Dictionary    file=${file_data}
    ${resp}=    Post Request    ${test_session}    /anything    files=${files}    data=${data}
    Should Be Equal As Strings    ${resp.status_code}    200
```

**Comment by orlof** [comment]
That syntax creates a request that combines data and files, but it is not streaming (NICE TO HAVE) and request's file part is missing name (MUST) and filename (NICE TO HAVE) attributes.

Here is the beginning of file part by python requests library:
`Content-Disposition: form-data; name="source_file"; filename="test.txt"
`
 ...and here it is with the RF syntax:
` Content-Disposition: form-data; name="file"; filename="file"
`

There is probably some way to inject these attributes also with RF syntax, but I am wondering why robotframework-requests library modifies the functionality of python-requests instead of just providing the same functionality.

**Comment by orlof** [comment]
Perhaps something like this should work?

```
This should work
    @{creds}=  Create List  1234567890123456789012345678901234567890  ${EMPTY}
    Create Session  zamzar  https://sandbox.zamzar.com/v1/  auth=${creds}

    &{data}=  Create Dictionary  target_format=txt

    ${file}=  Get File For Streaming Upload  test.txt
    &{files}=  Create Dictionary  source_file=${file}
    ${resp}=  Post On Session  zamzar  jobs  files=${files}  data=${data}

```

**Comment by cmin764** [comment]
Started investigating it more deeply using this [example](https://github.com/cmin764/robots/blob/main/http-requests/tasks.robot).

**Comment by cmin764** [comment]
Closing this, please re-open if there's still an issue with the library.
