### ISSUE TITLE
Documentation: Implement flake8 rst docstring linting

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#546]
Outside of the scope: can't we place this `E501` under the `ignore` of _config/flake8_ and just have this ignored globally? Since is a "line too long" error, maybe we can define a "per-docstring-ignore" if that would be possible.

Just food for thought if these can help here:
- https://pypi.org/project/flake8-docstrings/
- https://pypi.org/project/flake8-rst-docstrings/

_Originally posted by @cmin764 in https://github.com/robocorp/rpaframework/pull/544#discussion_r899002551_

**Comment by cmin764** [comment]
Makes a lot of sense!

**Comment by blakewaud** [comment]
Okay, so I will create a new issue to specifically address implementing rst docstring linting as the title of this issue and the contents are not in line.
