### ISSUE TITLE
`RPA.Robocorp.WorkItems` detect input/output item size limit exceeding

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#559]
Detect, during development, if we exceed the Work Item size limit enforced by Control Room for both the used _inputs_ and created _outputs_ per:
- payload
- individual attached files
- total size

And issue a warning if such limit is exceeded. (keep the warnings for output items in CR as well)

### References

Slack [thread](https://robocorp-developers.slack.com/archives/C028T0U4B53/p1655967093101159?thread_ts=1655966733.511589&cid=C028T0U4B53)

**Comment by bendersej** [comment]
Note that Control Room already prevents any payload size > 100KB (the current limit)

[As visible here in the code](https://github.com/robocorp/robocloud-logic/blob/master/task-data-api/sls/src/handlers/handlePutWorkItemPayload.ts#L23)

_Note that this link is only accessible to members of the repository_

**Comment by cmin764** [comment]
After speaking with @kariharju we agreed that this might not be the best place to put CR related limitations, as when they change we need to do changes in the library as well (for local dev).

A good solution will read them from a public endpoint. So please re-open if we decide to prioritise this.
