### ISSUE TITLE
Standardize Invoke commands

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#565]
Gathering here all Invoke related improvements (and Makefile replacements):

- https://github.com/robocorp/rpaframework/issues/564
- https://github.com/robocorp/rpaframework/issues/547
- https://github.com/robocorp/rpaframework/issues/482
- https://github.com/robocorp/rpaframework/issues/552
- https://github.com/robocorp/rpaframework/issues/566
- https://github.com/robocorp/rpaframework/issues/556
- https://github.com/robocorp/rpaframework/issues/613

**Comment by blakewaud** [comment]
First step is to consider common VSCode tooling for `invoke` like the scripting buttons available for `npm`/`yarn`. This should likely be a blocking epic.

**Comment by blakewaud** [comment]
Based on research, there is only one VSCode tool for `invoke` and it is not being actively maintained.

**Comment by cmin764** [comment]
I believe we can close this epic now and leave to be solved the other Issues which have their own Issue resource now.
