### ISSUE TITLE
Invoke cleanup can skip the venv removal

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#566]
I find it tedious and time consuming to have my _.venv_ removed each time I'm publishing a tiny fix in a package. Is it safe to add a `venv` flag on the `clean` task (and its invokers) so each time we (in)directly call `clean` we have the option to skip _.venv_ cleanup?

**Comment by blakewaud** [comment]
My understanding was this complete removal was to account for the possibility of contaminated `venv` environments during development. We could add a flag, but for the publish task, I do have some slight concerns about that, especially since I created the `install-local`  task which produces a `venv` that doesn't match the to be published package's `pyproject.toml` or lock file.

**Comment by cmin764** [comment]
I see, so we might risk going forward with a persistent _.venv_ which might trick the tests and have a chance at publishing potentially hidden issues? What if we keep the _.venv_ for `publish --ci` only?

Anyway, the `install-local` is available in the **meta** package (and we don't publish with that). Also, every time I manually edited the _.venv_, publishing was complaining about some subpaths mismatching and I could't even `build` the package in the first place (so that prevented me publishing with a non-clean _.venv_). But if I'm the only one feeling I'm wasting time with _.venv_ recreation each time we `publish`, then we can close this issue as _won't fix_.

**Comment by cmin764** [comment]
Will definitely save a lot of time from manually going to edit my _tasks.py_ scripts beforehand every time I'm CI-publishing, because me personally, will never allow myself to waste time on _.venv_ recreation without a sane reason.

**Comment by cmin764** [comment]
To clarify on this:
1. `.venv` removal should happen if you explicitly pass an argument to the `clean` command on doing it. (as it poses many headaches to recreate the .venv each time if that's not happening as it should on the system -- example: recreation of the .venv will use by default Python 3.10 but I want it created manually with Python 3.9.13, place where I use `poetry env use <path/to/python>` initially; and invoke doesn't do that for me)
2. Tests won't be executed with `--ci` param since I'm only interested into pushing the package to our PyPI for testing purposes. (later on when I decide to really push in prod, then yes, I expect to have the entire pipeline running including tests)

Don't you think we'll save dev time like that @mikahanninen / @blakewaud / @osrjv ?

**Comment by blakewaud** [comment]
Taking a look again, and with regards to your point 1, the meta-package `tasks.py` already allows for the use of `clean --no-venv`. I think it makes sense to add similar flags at the package level and implement similar flags on `publish` that only work when `--ci` is used.

**Comment by cmin764** [comment]
This is possible now with: `inv install.clean --no-venv` and publishing into CI with: `inv build.publish --ci --no-build`.
