### ISSUE TITLE
RPA.Windows locator offset does not work as expected

### ISSUE THREAD

**Issue by MatsKruger** [robocorp/rpaframework#587]
I have tried making a robot which uses `RPA.Windows` the `offset`in a locator.
The offset is way off.

For an example i used the calculator.

```
Control Window    name:Calculator
Click    name:Calculator> id:136    # Does as expected. Clicks center of element
Sleep    2s
Click    name:Calculator> id:136 offset:0,0    # Not as expected. Clicks way out of window
Sleep    2s
Click    name:Calculator> id:136 offset:-300,-300    # Not as expected. Clicks way out of window
```

**Comment by cmin764** [comment]
I can confirm, even our [test](https://github.com/robocorp/rpaframework/blob/master/packages/windows/tests/robot/test_windows.robot#L127-L128) is highlighting the fact there's something shady out there.

Working on a fix!

**Comment by MatsKruger** [comment]
Happy to hear that it is not just me.
Looking forward for a fix.
In the meanwhile I have attained the same result by using `RPA.Windows.Get Element` to get `left, top, right, bottom`. And then using `RPA.Desktop.Click`.

Just if anybody ends up in the same situation.

```
${elm}    RPA.Windows.Get Element    class:DTPicker20WndClass type:Pane index:2
RPA.Desktop.Click    point:${elm.left + 10},${elm.top + 10}
```

**Comment by cmin764** [comment]
> Happy to hear that it is not just me. Looking forward for a fix. In the meanwhile I have attained the same result by using `RPA.Windows.Get Element` to get `left, top, right, bottom`. And then using `RPA.Desktop.Click`.
> 
> Just if anybody ends up in the same situation.
> 
> ```
> ${elm}    RPA.Windows.Get Element    class:DTPicker20WndClass type:Pane index:2
> RPA.Desktop.Click    point:${elm.left + 10},${elm.top + 10}
> ```

Thank you for this. Also we just released a fix with the current `RPA.Windows` library through the latest `rpaframework==15.5.0`. Let me know if this new release and Windows fix works for you without relying on the deprecated one.
