### ISSUE TITLE
Legacy "Robocloud" mixed with "Robocorp" during service init from Vault (Google, AWS, Azure)

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#635]
<img width="901" alt="Screenshot 2022-09-19 at 17 16 55" src="https://user-images.githubusercontent.com/709053/191039383-d6743da4-6296-4ccf-9fc4-cabfe427c285.png">

And in `RPA.Cloud.Google` we've got this mix as well in the docstrings. (_keywords/context.py_)
- `init_service` & `init_service_with_object`
- `get_secret_from_robocorp_vault` while raising:
```
KeyError: "Both 'robocorp_vault_name' and 'robocorp_vault_secret_key' are required to access Robocorp Vault. Set them in library init or with `set_robocloud_vault` keyword."
```

**Comment by mikahanninen** [comment]
Google and AWS should be ok now.

**Comment by cmin764** [comment]
> Google and AWS should be ok now.

Nice, feel free to mark it as Done and close the Issue once it gets reelased.

**Comment by cmin764** [comment]
I saw Azure still remained with the problem, I can look into that one as well.
