### ISSUE TITLE
Include the private PyPI Portal example script in the library

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#640]
On [this](https://robocorp.com/portal/robot/robocorp/example-private-pypi) Portal example we have a script called [private-pip-install.py](https://github.com/robocorp/example-private-pypi/blob/master/bin/private-pip-install.py) which can be included in the library and maintained there.

Then the robot example _robot.yaml_ will refactor from:
```yaml
preRunScripts:
  - private-pip-install.py private_pypi requirements-private.txt
```
into something like
```yaml
preRunScripts:
  - python -m RPA.pip --vault private_pypi --secrets pypi_usr,pyp_pwd requirements-private.txt
```

### Notes
- Since the script uses `RPA.Robocorp.Vault` it is mandatory to have at least `rpaframework` in the _conda.yaml_.
  - This way the access to an `RPA.pip` module is ensured.
- We'll see if there's any struggle with adopting the current Portal example into the customer's needs and based on that we decide if this Issue makes sense or not. (since the example might be already convenient and flexible enough)

**Comment by tonnitommi** [comment]
Have not received requests for this, closing now.
