### ISSUE TITLE
Disable mouse movement simulation on `RPA.Windows.Select` keyword

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#686]
Original issue report in Dev Slack [post](https://robocorp-developers.slack.com/archives/CVBU007LN/p1667552240451179)

The `RPA.Windows.Select` needs to call `uiautomation.ComboBoxControl.Select` with `simulateMove=False`

Possible new keyword to add into a library.
```python
def select_combobox(self, locator, list_item_name):
        element = self.get_element(locator)
        element.item.GetExpandCollapsePattern().Expand()

        for child in element.item.GetChildren():
            if child.ControlTypeName != 'ListControl': continue

            for list_item in child.GetChildren():
                if list_item.Name != list_item_name: continue

                list_item.GetSelectionItemPattern().AddToSelection()
```

**Comment by cmin764** [comment]
Closing this as the bug was fixed by passing in the mouse movement simulation flag to the `Select` keyword. Will create a new feature request Issue if the current keyword is not enough on operating combo-boxes.
