### ISSUE TITLE
Offer background action keywords in `RPA.Windows`

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#690]
Allow users to set the library in background mode so automations are not visible to the user and the user can continue to work on other things while automation is running. We may have to also offer keywords to block input during specific moments so if they are typing it doesn't go into the automation at the same time.

This supports the assistant/unattended use case where a user wants to start an automation and perform other tasks while it runs.

**Comment by blakewaud** [comment]
This use case came to use from a customer utilizing some other RPA technologies which are able to do this, but they cannot replicate that behavior with our libraries. I agree with you generally that this seems like it creates those conflicts, but it's been implemented elsewhere so it must be possible.

**Comment by tonnitommi** [comment]
We should consider supporting Assistants that do not block user in Picture in Picture way. It's not a library thing.
