### ISSUE TITLE
`RPA.Email.Exchange` support for handling multiple accounts

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#702]
There's a use-case where multiple accounts need to be used for authorizing through the **OAuth2** flow with each one of them and sending e-mails with the active one, while having the token updated in the right place during the auto-refresh.

Customer [thread](https://robocorp-developers.slack.com/archives/C028T0U4B53/p1668410487673539?thread_ts=1667555683.961129&cid=C028T0U4B53)

----

I feel this might be overengineering, because the usual scenario is differentiating between dev & prod accounts to send e-mails with, so this problem can be solved cleaner by switching an env var ON when running in production and based on that the robot will pick the production User e-mail (eg.: from Work Item, env var or even Vault) and the production set of Client credentials (production Vault).

If we go this route, then the current state of the library knows where to update the token on auto-refresh, as currently that place is specified during the [importing](https://github.com/robocorp/example-oauth-email/blob/master/tasks.robot#L30-L31) of the library only:
```robotframework
Library    RPA.Email.Exchange    vault_name=${secret_name}    vault_token_key=token
```

**Comment by tonnitommi** [comment]
Not planned.
