### ISSUE TITLE
`RPA.Browser.Playwright` docs links lead to `400 Bad Request` (due to bad URL path)

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#718]
Surf to [Open Browser](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-playwright/keywords#open-browser) and click over the linked [New Page](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-playwright/%PATH%/keywords#new-page):

<img width="1117" alt="open-browser" src="https://user-images.githubusercontent.com/709053/205317798-87aa91a8-09bf-42e8-a1fb-d0fd4adaa293.png">

<img width="1040" alt="new-page" src="https://user-images.githubusercontent.com/709053/205317829-fa8c7d64-6e4f-4795-a140-27ec9338b7e9.png">

From where that `%PATH%` comes from in the URL? Maybe our `invocations.docs.build_docs` builder fails to somehow populate this Windows-like env var or what is supposed to be.

----

From rpaframework.org this works correctly: [Open Browser](https://rpaframework.org/libdoc/RPA_Browser_Playwright.html#Open%20Browser) -> [New Page](https://rpaframework.org/libdoc/RPA_Browser_Playwright.html#New%20Page)

**Comment by cmin764** [comment]
@TimothyLopas / @blakewaud do you have any wild guess on this one?

**Comment by rihardsgravis** [comment]
Yeah I do. There is some additional logic added to the keyword documentation links in Robocorp Documentation as it is split in multiple pages rather than one (which is the case for the source documentation). There is a bug somewhere in there, I'll take a look and fix it.
