### ISSUE TITLE
RPA.Excel.Application find_first_available_row error

### ISSUE THREAD

**Issue by dmreinoso** [robocorp/rpaframework#72]
So I have an Excel file with some data in it and I am trying to know the first row.

from RPA.Excel.Application import Application
app = Application()
app.open_application(True)
app.open_workbook(r"C:\Users\User\Downloads\file.xlsx")
free_row = app.find_first_available_row("Sheet1")

And get this error:

Traceback (most recent call last):
  File ".\rpa_test.py", line 12, in <module>
    tupla_libre = app.find_first_available_row("Sheet1")
  File "C:\proyectos\rpa_pruebas\.venv\lib\site-packages\RPA\Excel\Application.py", line 120, in find_first_available_row
    cell_value = worksheet.Cells(row, column).Value
AttributeError: 'str' object has no attribute 'Cells'

I am using rpaframework==6.4.0
Windows 10 64bits

**Comment by mikahanninen** [comment]
Thank you for the report @dmreinoso ! This will be fixed in the next release.

**Comment by mikahanninen** [comment]
Fixed in release 6.5.0
