### ISSUE TITLE
Add support for Java GUI (Swing/AWT) in Desktop.Windows library

### ISSUE THREAD

**Issue by ndsulit** [robocorp/rpaframework#73]
Any future support for Java GUI? The Desktop.Windows library seems only works for Windows Form.

**Comment by osrjv** [comment]
I think we'll be supporting (at least) Java Swing applications in the future, and I'm going to include this in the roadmap for tracking. No information yet on schedules.

Note that there's a separate [SwingLibrary](https://github.com/robotframework/SwingLibrary) already. Another option is to use image-based automation with `RPA.Desktop`, but that's of course less robust.

**Comment by ndsulit** [comment]
@osrjv Awesome! Looking forward for it. Thanks a lot for the possible workaround 👍

**Comment by mchece** [comment]
Java Swing could be possible, but then you have Oracle Forms too - those are bit different. In any case this should be cross-platform, not only working on Windows.

**Comment by osrjv** [comment]
Recently we added a separate library called JavaAccessBridge: https://rpaframework.org/libraries/javaaccessbridge/index.html
