### ISSUE TITLE
Improve `RPA.core.logger.deprecation`

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#739]
Function [code](https://github.com/robocorp/rpaframework/blob/master/packages/core/src/RPA/core/logger.py#L15-L21)

### ToDo
- ~[ ] By default should emit [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning). And with a set argument like `future=True` should emit [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning).~
- [ ] A `date` keyword argument with which you can specify in which next major version release after the specified date, the support for this drops completely.

### Next
- Optional: Add an invocations checker which looks, during the package build, for stuff that was marked as deprecated. And verifies if it was taken out given the current date and the major package version that is about to be released now.
  - If such a deprecation message over the specified date is still found, the builder fails. So you have to remove the message and drop that functionality in order to be able to build it. (otherwise we forget to remove deprecated features on time)
- Remove all the deprecated features marked so far with this call. (if they were present long enough to be considered dead by now)

**Comment by tonnitommi** [comment]
Improve our dev process, no immediate needs for features.
