### ISSUE TITLE
Downloads consuming disk space on systems

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#741]
Downloads done via the Browser libraries (`RPA.Browser.Selenium` and `RPA.Browser.Playwright`) using the default `Downloads` directory causes excessive disk space usage on VMs because the `Downloads` directory is outside of the robot's local working folders. We should either develop best practices for developers to follow to set the download path to a local folder or we should see about setting the default from the common library upon load.

**Comment by cmin764** [comment]
Agree, but setting a robot inner download dir implicitly (like `${OUTPUT_DIR}${\}download`) might be a breaking change or cause the exposure of unwanted files.

Still, this goes hand in hand with the `Set Download Directory` improvement: https://github.com/robocorp/rpaframework/issues/882

**Comment by cmin764** [comment]
I will close this for now, let's see if somebody from the cloud side like @eprnn / @ovatto complains about the container size, or let me know @blakewaud if you have any fresh insights given this, so I'll re-open and set it as breaking change and potential security concern (given that the downloaded files will be found in another place now).
