### ISSUE TITLE
RPA.Dialogs "Add File Input" file_type does not allow "." character before parenthesis

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#743]
e.g.
`Add file input  name=anything  label=Label  file_type=.robot files only (*.robot)  multiple=False`

does not open file dialog window (tested in mac and windows).

**Comment by orlof** [comment]
```
*** Settings ***
Library  RPA.Dialogs

*** Tasks ***
Minimal task
    Add file input  name=anything  file_type=.robot files only (*.robot)
    Run dialog
```

**Comment by tonnitommi** [comment]
`RPA.Dialogs` is replaced by `RPA.Assistant`. No further updates to be done to RPA.Dialogs (except security related).
