### ISSUE TITLE
`RPA.Browser.Playwright` needs keywords to wrap new browsers

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#748]
The Playwright library's method to create a new browser for automation can be confusing because it requires the user to use three different keywords to configure the browser as they wish, as well as the default turns off downloads, which is likely unexpected for most RPA developers.

We need a keyword that wraps the `New browser`, `New context`, and `New Page` into a single keyword that also sets `acceptDownloads` to `True`. The keyword should also expose all the parameters available to the underlying keywords as well. The existing combination keyword will throw warnings that it is for debug purposes only so it is not acceptable for this purpose.

**Comment by tonnitommi** [comment]
These changes should be done in the Robot Framework Browser library. Closing for rpaframework.

**Comment by tonnitommi** [comment]
Check out: https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Persistent%20Context
