### ISSUE TITLE
How can I walk thru a tree of Windows 

### ISSUE THREAD

**Issue by hhsem** [robocorp/rpaframework#779]
In RPA.Windows I can get the tree printed by "Print tree" but how can I step thru the tree and get each treeItem as element  with the level-information so I can  "Click" on and find additional information on the window.  I can only see a solution by using python but is there any solution just using the key words of RPA.Windows ?

**Comment by cmin764** [comment]
Hi, indeed as you already observed, there's no direct RF support for that, but you can replicate the code in `Print Tree` under Python and extend the library yourself with a keyword (Py method) that can be used further in your bots. (so you'd still use RF for calling it at least)

Otherwise, [Get Elements](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows/keywords#get-elements) might pose a great fit for your case, then you can run commands over all the returned `WindowsElement`s.

----

Still, if you feel that this behavior should be officially supported and wrapped by the library and directly usable from RF, can you please elaborate on the use-case?

**Comment by hhsem** [comment]
Thank you for your reply!

I will try to follow your suggestion.  If I am the only one which hast he problem to walk thru a tree than it is not required to find an official solution.
Thank you


Von: Cosmin Poieana ***@***.***>
Gesendet: Montag, 23. Jänner 2023 08:18
An: robocorp/rpaframework ***@***.***>
Cc: Semmelmayer, Herbert ***@***.***>; Author ***@***.***>
Betreff: Re: [robocorp/rpaframework] How can I walk thru a tree of Windows (Issue #779)


Hi, indeed as you already observed, there's no direct RF support for that, but you can replicate the code in Print Tree under Python and extend the library yourself with a keyword (Py method) that can be used further in your bots. (so you'd still use RF for calling it at least)

Otherwise, Get Elements<https://robocorp.com/docs/libraries/rpa-framework/rpa-windows/keywords#get-elements> might pose a great fit for your case, then you can run commands over all the returned WindowsElements.

________________________________

Still, if you feel that this behavior should be officially supported and wrapped by the library and directly usable from RF, can you please elaborate on the use-case?

**Comment by hhsem** [comment]
The use case is : start program keepass and look for all groups (all levels because a group can be part of a group).
The second step is to start with the first group and look at all entries which belong to the group. After this move to the next group in the tree.
The program keepass is freeware.
I tried to use "Get Elements" to find all groups but will not get to the next level.
With the first group i failed also to get all entries which belong to the group.

Enclosed you find all programs to reproduce my problem:
To list the groups:

*** Settings ***
Library    RPA.Windows
Library    RPA.FileSystem

*** Variables ***
${NL}			\n
${TAB}			\t
*** Tasks ***
List Groups
	Control Window		regex:".*KeePass$"
	${FileExists} =    Does file exist   ListGroups
	IF   ${FileExists}
		Remove File   ListGroups
	END
	Create file   ListGroups   content=List Of Groups\n
	Set Anchor	type:TreeItem name:AutoDb
	@{Groups} =   Get Elements   type:TreeItem
	FOR  ${Group}  IN  @{Groups}
		Log To Console   "LEVEL-1:" ${Group.name}
		${Line}   Create List	${Group.name}
		Append To File   ListGroups   content=${TAB}
		Append To File   ListGroups   content=${Line}
		Append To File   ListGroups   content=${NL}
		
		@{SubGroups} =   Get Elements	${Group}	search_depth=1
		FOR	${SubGroup}	IN	@{SubGroups}
			IF	${Group} != ${SubGroup}
				Log To Console   "LEVEL-2: " ${SubGroup.name}
		
				@{SubGroups2} =   Get Elements	${SubGroup}	search_depth=1
				FOR	${SubGroup2}	IN	@{SubGroups2}
					Log To Console   "LEVEL-3: " ${SubGroup2.name}
				END
			END
		END
	END



To find the entries:

*** Settings ***
Library    RPA.Windows
Library    RPA.FileSystem

*** Variables ***
*** Tasks ***
Create Entry of Group
	Control Window		regex:".*KeePass$"
	Print Tree	log_as_warnings=${True}
	Set Anchor	type:TreeItem name:AutoDb
	Click		name:SEMM02
	Click		id:ListViewItem-1
	${element} =	Get Element		id:ListViewSubItem-0
	$[entries} =	Get Elements
	FOR		${entry}	IN	@{entries}
		Log To Console   "LEVEL-1:" ${entry.name}
	END

**Comment by cmin764** [comment]
If you're planning to search for elements under `${SubGroup}`, then you should pass that as a `root_element=` param to the keyword and pass as the first argument a proper string-based locator which identifies your elements by class/type. Also try switching the `siblings_only` to `False` if you're searching globally at any level in the tree.

I'm closing this as the tree of elements problem can by solved by using [Get Elements](https://robocorp.com/docs/libraries/rpa-framework/rpa-windows/keywords#get-elements) with proper passed in locator, root element and siblings switch values.

**Comment by hhsem** [comment]
I send you again my program because I am not happy with the solution. I am a beginner and worked hours to get a solution but I can not find a good one. My  solution is example 1: I walk thru the elements starting with "AutoDb"  and get all groups but I can not see the structure: which group belogs to which group e.g "SEMM2.1" belongs to "SEMM02" as one can see by the Print Tree. I think It would be helpful if one get the level of the element as information. Best as property of the element in case of  keyword "Get element".
What is your suggestion?


kw name="Print Tree" library="RPA.Windows">
<arg>name:AutoDb</arg>
<arg>8</arg>
<arg>inhalt</arg>
<arg>True</arg>
<doc>Print Control element tree.</doc>
<msg timestamp="20230131 11:27:55.102" level="INFO">Getting element with locator: name:AutoDb</msg>
<msg timestamp="20230131 11:27:55.104" level="INFO">Resulted root element: WindowsElement(item=&lt;uiautomation.uiautomation.WindowControl object at 0x00000176490621C0&gt;, locator='name:"AutoDb.kdbx - KeePass" and type:WindowControl', name='AutoDb.kdbx - KeePass', automation_id='MainForm', control_type='WindowControl', class_name='WindowsForms10.Window.8.app.0.30495d1_r6_ad1', left=527, right=1197, top=146, bottom=671, width=670, height=525, xcenter=862, ycenter=408)</msg>
<msg timestamp="20230131 11:27:55.105" level="INFO">Locator 'name:AutoDb' produced matcher: MatchObject(locators=[('Name', 'AutoDb', 0)], _classes=set(), max_level=0)</msg>
<msg timestamp="20230131 11:27:55.513" level="INFO">Returning element: WindowsElement(item=&lt;uiautomation.uiautomation.TreeItemControl object at 0x00000176491A5670&gt;, locator='name:AutoDb', name='AutoDb', automation_id='', control_type='TreeItemControl', class_name='', left=559, right=606, top=228, bottom=246, width=47, height=18, xcenter=582, ycenter=237)</msg>
<msg timestamp="20230131 11:27:55.549" level="WARN">ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (559,228,606,246)[47x18]    Name: 'AutoDb'    Handle: 0x0(0) [50024_1.png]</msg>
<msg timestamp="20230131 11:27:55.596" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,246,622,264)[44x18]    Name: 'General'    Handle: 0x0(0) [50024_2.png]</msg>
<msg timestamp="20230131 11:27:55.667" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,264,631,282)[53x18]    Name: 'Windows'    Handle: 0x0(0) [50024_3.png]</msg>
<msg timestamp="20230131 11:27:55.730" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,282,623,300)[45x18]    Name: 'Internet'    Handle: 0x0(0) [50024_4.png]</msg>
<msg timestamp="20230131 11:27:55.783" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,300,611,318)[33x18]    Name: 'eMail'    Handle: 0x0(0) [50024_5.png]</msg>
<msg timestamp="20230131 11:27:55.832" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,318,658,336)[80x18]    Name: 'Homebanking'    Handle: 0x0(0) [50024_6.png]</msg>
<msg timestamp="20230131 11:27:55.880" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,336,640,354)[62x18]    Name: 'Recycle Bin'    Handle: 0x0(0) [50024_7.png]</msg>
<msg timestamp="20230131 11:27:55.946" level="WARN">        ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (597,354,646,372)[49x18]    Name: 'Network'    Handle: 0x0(0) [50024_8.png]</msg>
<msg timestamp="20230131 11:27:55.996" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,372,628,390)[50x18]    Name: 'SEMM02'    Handle: 0x0(0) [50024_9.png]</msg>
<msg timestamp="20230131 11:27:56.051" level="WARN">        ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (597,390,656,408)[59x18]    Name: 'SEMM02.1'    Handle: 0x0(0) [50024_10.png]</msg>
<msg timestamp="20230131 11:27:56.116" level="WARN">            ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (616,408,684,426)[68x18]    Name: 'Semm02.1.1'    Handle: 0x0(0) [50024_11.png]</msg>
<msg timestamp="20230131 11:27:56.164" level="WARN">        ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (597,426,656,444)[59x18]    Name: 'Semm02.2'    Handle: 0x0(0) [50024_12.png]</msg>
<msg timestamp="20230131 11:27:56.213" level="WARN">    ControlType: TreeItemControl    ClassName:     AutomationId:     Rect: (578,444,628,462)[50x18]    Name: 'SEMM03'    Handle: 0x0(0) [50024_13.png]</msg>
<status status="PASS" starttime="20230131 11:27:55.099" endtime="20230131 11:27:56.222"/>
</kw>


And now my Example1:
*** Settings ***
Library     RPA.Windows
Library     RPA.FileSystem


*** Tasks ***
List Groups
    Control Window    name:"AutoDb.kdbx - KeePass"
    ${FileExists} =    Does file exist    ListGroups
    IF    ${FileExists}    Remove File    ListGroups
    Create file    ListGroups    content=List Of Groups\n
    Print Tree    name:AutoDb    8    inhalt    True
    ${Root} =    Get Element    AutoDb
    Log    ${Root}    console=True
    Set Anchor    type:TreeItem name:AutoDb
    @{Groups} =    Get Elements    search_depth=16    siblings_only=False
    FOR    ${Group}    IN    @{Groups}
#    Log To Console    ${Group}
        Log To Console    ${Group.name}
        ${Line} =    Create List    ${Group.name}
        Append To File    ListGroups    content=${Line}
        Append To File    ListGroups    content=${\n}
        IF    '${Group.name}' == 'SEMM02'
            @{SubGroups} =    Get Elements    root_element=${Group}    search_depth=16    siblings_only=False
            FOR    ${SubGroup}    IN    @{SubGroups}
                Log TO Console    "SubGroup"
                Log To Console    ${SubGroup}
            END
        END
    END



The list of ListGroups:

List Of Groups
['AutoDb']

['General']

['Windows']

['Internet']

['eMail']

['Homebanking']

['Recycle Bin']

['Network']

['SEMM02']

['SEMM02.1']

['Semm02.1.1']

['Semm02.2']

['SEMM03']

**Comment by hhsem** [comment]
My mistake - the example 1 is

*** Settings ***
Library     RPA.Windows
Library     RPA.FileSystem


*** Tasks ***
List Groups
    Control Window    name:"AutoDb.kdbx - KeePass"
    ${FileExists} =    Does file exist    ListGroups
    IF    ${FileExists}    Remove File    ListGroups
    Create file    ListGroups    content=List Of Groups\n
    Print Tree    name:AutoDb    8    inhalt    True
    ${Root} =    Get Element    name:AutoDb
    Log    ${Root}    console=True
#    Set Anchor    type:TreeItem name:AutoDb
    @{Groups} =    Get Elements    search_depth=16    root_element=${Root}    siblings_only=False
    FOR    ${Group}    IN    @{Groups}
        Log To Console    ${Group}
        Log To Console    ${Group.name}
        ${Line} =    Create List    ${Group.name}, ${Group.left}
        Append To File    ListGroups    content=${Line}
        Append To File    ListGroups    content=${\n}
        ${Line} =    Create List    ${Group}
        Append To File    ListGroups    content=${Line}
        Append To File    ListGroups    content=${\n}
    END
