### ISSUE TITLE
RPA.Windows select action keyword simulates mouse movement by default

### ISSUE THREAD

**Issue by magrosso** [robocorp/rpaframework#791]
The select keyword in action module calls the windows automation library with default mouse movement simulation turned on (simulateMove=True). This does not work for our application, it is way too slow and causes many wrong combobox selections.

Selection works if we turn off mouse movement simulation by calling instead:
element.item.Select(value, simulateMove=False)

I would think that turning mouse simulation off is a better default setting, because it is faster and more reliable.
It may even be helpful to have "simulateMove" as an API parameter so that the test author can decide whether they want to move the mouse or not.

**Comment by mikahanninen** [comment]
Yeah, I agree that simulateMove should be configurable by the user. 

The problem with `Select `is that there are different implementations for that depending on what kind of control element is in question. Only `ComboBoxControl `allows setting mouse simulation on or off and there it is by default `True`.

And you can do this...

> Selection works if we turn off mouse movement simulation by calling instead:
> element.item.Select(value, simulateMove=False)

.. your element seems to be a ComboBox.

We will look into allowing configuration simulateMove everywhere it is applicable.

**Comment by magrosso** [comment]
Great, thanks.
Correct, it's a combobox! Looking into the uiautomation code, there are a few actions (e.g. click, drag_and_drop) that move the mouse per default before the actually act. I suspect, we will have the same problem with those. Can we have it user configurable for all actions that (needlessly) move the mouse?

**Comment by magrosso** [comment]
Or even make it global setting like global timeout:
set_mouse_movement(move=True|False)

**Comment by cmin764** [comment]
That sounds like a valid keyword, I'm aiming for introducing a `Set Mouse Movement       True|False` keyword which will enable or disable this simulation for the actions following it.

**Comment by magrosso** [comment]
That setting would be valid for all actions until the next setting, right?
