### ISSUE TITLE
`RPA.Windows.Control Window` problem on older Windows versions

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#797]
**description of the issue**
The reported occurrence happens on Windows Server 2012 where `Control Window` just activates the application icon in the Task Bar but does not get control of the window nor bring the window to the foreground.

**analysis**
The control of the window can be achieved by an alternate way of setting the window for the library instance via accessing elements returned by `List Windows` keyword. 

requires still more investigation

**Comment by cmin764** [comment]
@mikahanninen Can you check if the library version `>=21.0.1` already fixed this? ([commit](https://github.com/robocorp/rpaframework/commit/79dee7b89c590267a5d62f5b719e88d3168e9080#diff-0a7283994d97702e55c06386dbbdf83eacdde8f26b6189fc9a14b638ad977d26L298-L300))

Or giving me access into a 2012 Windows Server so I can check it myself.
