### ISSUE TITLE
RPA.Email.ImapSmtp.List Messages - encoding codec that couldn’t be read

### ISSUE THREAD

**Issue by AlexisxCapto** [robocorp/rpaframework#801]
`KEYWORD @{emails2} = RPA.Email.ImapSmtp . List Messages TEXT "Please find enclosed your bank statement" SINCE ${time}
Documentation:	
Return list of messages matching criterion.

Start / End / Elapsed:	20230130 10:44:29.645 / 20230130 10:44:30.581 / 00:00:00.936
10:44:29.877	INFO	IMAP search: 'TEXT "Please find enclosed your bank statement" SINCE 31-Dec-2022'	
10:44:30.565	FAIL	LookupError: unknown encoding: None`
 
See below the email information:
SUBJECT: Банково извлечение / Bank statement BG09XXXXX No 1 / dd.mm.yyyy
From: [bank_statements@unicreditgroup.bg](mailto:bank_statements@unicreditgroup.bg)
Attachment: OOO_52_20230125_C_BGxxxxxxxxxxxx_1_518XXXX23025005X.pdf

**Comment by mikahanninen** [comment]
Following email searches should work with encoding

```robotframework
${emails}=    List Messages    literal:TEXT "Please find enclosed your bank statement"
${emails}=    List Messages    literal:SUBJECT "Банково извлечение"
```

**Comment by mikahanninen** [comment]
Closed for inactivity.
