### ISSUE TITLE
Error in `RPA.JSON` extended keyword example attached to `Get Values from JSON`

### ISSUE THREAD

**Issue by blakewaud** [robocorp/rpaframework#804]
The example calls the `str()` function but does not encapsulate the function call in backticks, so it fails when ran exactly as stated in the example. The pattern should be updated to match the following:

```
$.clients[*].orders[*].id + " has price " + $.clients[*].orders[*].price.`str()`
```

**Comment by tonnitommi** [comment]
Example is here: https://robocorp.com/docs/libraries/rpa-framework/rpa-json/keywords#get-values-from-json

**Comment by cmin764** [comment]
[Fixed](https://github.com/robocorp/rpaframework/commit/10882cf2d01010d2b96f48b2dd5c825ecd64b08e) it in two places with triple backticks ``` (screenshots from generated local docs):

<img width="880" alt="Screenshot 2023-02-15 at 18 57 34" src="https://user-images.githubusercontent.com/709053/219009116-c748f297-04c2-40aa-b53a-d0856303f8bb.png">

<img width="841" alt="Screenshot 2023-02-15 at 18 57 28" src="https://user-images.githubusercontent.com/709053/219009099-57b1713d-c667-4ba6-b8f2-7b5d6b26fd18.png">

**Comment by cmin764** [comment]
<img width="1080" alt="Screenshot_2023-02-15_at_19_35_38" src="https://user-images.githubusercontent.com/709053/219017129-328ce067-3820-4e30-bef5-7f2bd057591f.png">
