### ISSUE TITLE
RPA.Windows will loose information if the program under investigation ihas lost to be the top window

### ISSUE THREAD

**Issue by hhsem** [robocorp/rpaframework#806]
Hello please help me to understand why my walk thru of all groupd os the freewae program KeePass will sode information.
I start the VS to investigate all groups and there entries and write the information to a file "ListGroups". If I do not touch any key on the keyboard I get a good result. I do it again but after start switch to another Window so "Keepass" is not the top window anymore. Now I get a result where a lot of information is lost and I can see no error in the log.html.
The reason for the test is to see how RPA will handle a situation where some program pops up and how this situation can be handled. Because I got no error/worning in my keywords I would like to know how to handle such situation.
Thank you for your atttention.

The files are:
    First run with KeePass being all the time the top window
    SoleHtml.txt = log.html
    SoloOutputXml.txt = output.xml
    SoloListGroups.txt = the result file

    The 2nd run with force Keepass not be the top window
    LogHtml.txt = log.htmö
    OutputXml.txt = output.xml
    ListGroups.txt = result file

    ListGroupRobot.txt = ListGroup.robot

[SoloOutputXml.txt](https://github.com/robocorp/rpaframework/files/10675569/SoloOutputXml.txt)
[ListGroups.txt](https://github.com/robocorp/rpaframework/files/10675570/ListGroups.txt)
[LogHtml.txt](https://github.com/robocorp/rpaframework/files/10675571/LogHtml.txt)
[OutputXml.txt](https://github.com/robocorp/rpaframework/files/10675572/OutputXml.txt)
[SoloHtml.txt](https://github.com/robocorp/rpaframework/files/10675573/SoloHtml.txt)
[SoloListGroups.txt](https://github.com/robocorp/rpaframework/files/10675574/SoloListGroups.txt)
[ListGroupRobot.txt](https://github.com/robocorp/rpaframework/files/10675552/ListGroupRobot.txt)

**Comment by cmin764** [comment]
Hi @hhsem and thank you for reporting your findings!

I haven't tested it yet, but sometimes for the elements to appear (and be seen in Accessibility Insights as well), therefore be retrievable by our `Print Tree` / recorder, you have to focus on the app's window, even interact with the elements so they unfold themselves into the more details you've seen with the top-window case.

Would the workaround of making that window top-level each time you want to interact with (using `Control Window`) be sufficient for you here?
Next would be for us to replicate and seek improvements, but I have no ETA nor priority on this one for now.

**Comment by hhsem** [comment]
Thank you for your idea of a work around.
I am sorry that it is not working but maybe I did the change not like you suggested. If so please send me the part of coding which you would change.

The new result is:
List Of Groups
Group: AutoDb; Level=0
	 Title=Herbert05.1.5; User Name=herbert05; Password=********; URL=www.tenfold.com; Notes=Notes für Herbert3;
	 Title=Herbert03.1.5; User Name=herbert0; Password=********; URL=www.tenfold.com; Notes=Notes für Herbert3;
Group: Windows; Level=0
Group: eMail; Level=0
Group: Homebanking; Level=0
Group: Recycle Bin; Level=0
Group: Network; Level=0
Group: SEMM02; Level=0
Group: SEMM02.1; Level=0
Group: Semm02.1.1; Level=0
Group: Semm02.2; Level=0
Group: SEMM03; Level=0
Group: Internet; Level=0
Group: General; Level=0


The modified coding is:
*** Settings ***
Library     RPA.Windows
Library     RPA.FileSystem
Library     Collections
Library     RPA.Browser.Selenium


*** Tasks ***
List Groups
    ${Window} =    Control Window    regex:"AutoDb.kdbx.*KeePass"
#    Print Tree    log_as_warnings=True
    ${FileExists} =    Does file exist    ListGroups
    IF    ${FileExists}    Remove File    ListGroups
    Create file    ListGroups    content=List Of Groups\n
    ${Root} =    Get Element    name:AutoDb
    Log    ${Root}    console=True
    Set Anchor    type:TreeItem name:AutoDb
    ${Groups} =    Get Elements    search_depth=16    root_element=${Root}    siblings_only=False
    FOR    ${Group}    IN    @{Groups}
        Get a group and Output information    ${Group}    ${Window}
    END


*** Keywords ***
Get a group and Output information
    [Arguments]    ${Group}    ${Window}

    Log To Console    ${Group.name}
    Log    ${Group.name}
    ${Level} =    Create List
    ${CurLevel} =    Get Index From List    ${Level}    ${Group.left}
    IF    '${CurLevel}' < '0'
        Append To List    ${Level}    ${Group.left}
        ${CurLevel} =    Get Index From List    ${Level}    ${Group.left}
    END
    Append To File    ListGroups    content=Group: ${Group.name}; Level=${CurLevel}\n
    Click    ${Group}
    List Group    ${Window}

List Group
    [Arguments]    ${Window}

    ${Window} =    Control Window    regex:"AutoDb.kdbx.*KeePass"
    ${Entries} =    Get Element    id:m_lvEntries    root_element=${Window}
    Log    'List Group: Elements=',${Entries}
    Find entries of KeePass    ${Entries}

Find entries of KeePass
    [Arguments]    ${Entries}

    ${Spalten} =    Create List
    ${Window} =    Control Window    regex:"AutoDb.kdbx.*KeePass"
    ${Elements} =    Get Elements    search_depth=1    root_element=${Entries}    siblings_only=False
    ${LngElements} =    Get Length    ${Elements}
    Log    LengthOf Elements=${LngElements}
    FOR    ${Element}    IN    @{Elements}
        ${LngElements} =    Get Length    ${Elements}
        Log    Find entries of KeePass: ${Element.name} ${Element.control_type}
        IF    '${Element.control_type}' == 'HeaderControl'
            Get spalten    ${Element}    ${Spalten}
        ELSE IF    '${Element.control_type}' == 'ListItemControl'
            Get data of entry    ${Element}    ${Spalten}
        END
    END

Get spalten
    [Arguments]    ${Element}    ${Spalten}

    ${Window} =    Control Window    regex:"AutoDb.kdbx.*KeePass"
    ${infos} =    Get Elements    search_depth=1    root_element=${Element}    siblings_only=False
    ${Lng} =    Get Length    ${infos}
    Log    LengthOf Infos=${Lng}
    FOR    ${info}    IN    @{infos}
        ${Lng} =    Get Length    ${infos}
        Log    Get spalten: info=${info}
        IF    '${info.name}' == 'Headersteuerelement'
            Append To List    ${Spalten}    'Entry'
        ELSE
            Append To List    ${Spalten}    ${info.name}
        END
        Log    Get spalten: spalten=${Spalten}
    END

Get data of entry
    [Arguments]    ${Element}    ${Spalten}

    Log    Get data of entry: Spalten=${Spalten}
    ${Window} =    Control Window    regex:"AutoDb.kdbx.*KeePass"
    ${infos} =    Get Elements    search_depth=1    root_element=${Element}    siblings_only=False
    FOR    ${info}    IN    @{infos}
        Log    ${info}
        ${Ix} =    Get Index From List    ${infos}    ${info}
        Log    Get data of entry: Ix=${Ix}
        IF    ${Ix} == 0
            Append To File    ListGroups    content=\t
        ELSE
            ${Col} =    Get From List    ${Spalten}    ${Ix}
            Append To File    ListGroups    content= ${Col}=${Info.name};
        END
    END
    Append To File    ListGroups    content=\n

**Comment by hhsem** [comment]
The modification I have done makes the program very slow

**Comment by cmin764** [comment]
Hi again @hhsem and thank you for your patience on this!

We've done improvements meanwhile on the Windows library and with the latest `rpaframework==22.1.1` we managed to automate **Kee Pass 2** on Windows 11 ARM (through Parallels on Mac) with the following [robot](https://github.com/cmin764/robots/blob/main/desktop-auto/tasks.robot#L337-L366):
```robotframework
Get Entries From KeePass Group
    [Setup]    Windows Search    KeePass 2

    # Control KeePass window and log+print its element tree.
    Control Window    subname:"- KeePass"
    ${structure} =    Print Tree    return_structure=${True}
    Log To Console    ${structure}

    # Get all secret groups matching criteria. (belonging to the accepted names list)
    @{names} =    Create List    Test
    @{groups} =    Create List
    ${elems} =    Get Elements    name:Database > type:TreeItemControl
    FOR    ${elem}    IN    @{elems}
        ${status} =    Run Keyword And Return Status    Should Contain
        ...    ${names}    ${elem.name}
        IF    ${status}
            Append To List    ${groups}    ${elem}
        END
    END

    # Now print all the entries in every accepted group.
    FOR    ${group}    IN    @{groups}
        Log To Console    In group: ${group.name}
        ${elems} =    Get Elements    path:1|1|1|2|1 > type:ListItemControl
        FOR    ${elem}    IN    @{elems}
            Log To Console    Entry: ${elem.name}
        END
    END

    [Teardown]    Close Current Window
```

The robot simply opens and controls Kee Pass 2, then looks for some databases of interest and lists all the entries in them. Here's a demo recording:

https://user-images.githubusercontent.com/709053/223320014-75ad8ce9-f790-4909-aa3f-411305e90c44.mov

----

For further help please use our [Troubleshoot](https://forum.robocorp.com/c/troubleshooting/15) forum instead of opening GH Issues. Happy automating!
