### ISSUE TITLE
RPA.Desktop - OCR locator missing language parameter

### ISSUE THREAD

**Issue by velkrissz** [robocorp/rpaframework#826]
Image Locator using OCR is missing a language argument.
Without it, the OCR locator can not be used for non-English recognition.

I suggest two changes that could be added to improve usability:

1. Add a global setting for the default language for OCR. Eg.: at library initialization. (This is not sufficient as non-English apps may be launched on English OS and the robot might need to interact with both.)
2. Add a third argument (or a named one) for the OCR locator string. Eg.: ```ocr:"Ezt találd meg",75,hun``` (or ```ocr:"Ezt találd meg",lang=hun```)

I temporarily changed the RPA/recognition/ocr.py (line 64 in my case) in my local package to include a language parameter:
```data = pytesseract.image_to_data(image, lang="hun", output_type=pytesseract.Output.DICT)```
This significantly improved OCR for each keyword I used in the robot for Hungarian text recognition.

I hope this parameter can surface in keywords soon.

**Comment by velkrissz** [comment]
I'm not a Python developer but I implemented my second suggestion here: 02a72192ead020b982739e861548f40dbf77841f
As I am less familiar with the RPA codebase, I am not starting a merge request unless somebody confirms that my changes won't break something. (I added an optional parameter in the RPA core.)
Could someone take a look? It would be crucial for my project to add support for OCR languages.

**Comment by orlof** [comment]
Thanks for the report and PR. This is definitely a good improvement and we will proceed with it next week.
