### ISSUE TITLE
Add support for scraping

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#84]
Initial version should be able to do web scraping for elements on the page, especially tables using `BeautifulSoup` package.

Could be added as a new separate library or feature included into current libraries like `RPA.Browser` and `RPA.Desktop`

For future versions add support for scraping tables from images

**Comment by cmin764** [comment]
This is quite old, do we still want to add this feature? (which requires more details and scoping)

**Comment by mikahanninen** [comment]
There have been no requests that I have seen for the feature. I will close this one.
