### ISSUE TITLE
`RPA.Robocorp.Process` API endpoint is not considering instance defined by the user's profile

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#845]
**Problem**
User's RCC profile is pointing to the `eu2` instance of the Robocorp platform instead of default `eu1`, but library is still set to use `eu1` endpoint of the Process API.

**Solution**
The environment variable `RC_API_PROCESS_HOST` should be used when set (and library init parameter `robocorp_api_server` is not used).

**Comment by tonnitommi** [comment]
Already fixed
