### ISSUE TITLE
RF 6.x support?

### ISSUE THREAD

**Issue by EricBLivingston** [robocorp/rpaframework#866]
I installed RPA Framework and noticed it pulled my RF from version 6.0.2 down to 5.0.1

What's the timeline for moving RPA Framework to RF 6? I was looking to use the localization features and other capabilities of 6.x

**Comment by tonnitommi** [comment]
There is an [open issue](https://github.com/robocorp/rpaframework/issues/673) for this topic. I am closing this as a duplicate.
