### ISSUE TITLE
Library Ideas

### ISSUE THREAD

**Issue by xylix** [robocorp/rpaframework#87]
Mobile automation libraries:
- Appium 

Domain specific libraries:
- Jira
- Trello
- Word

Utility libraries:
- XML
- SSH
- LDAP, AD
- Crypto

?? libraries (Need more details):
- Java
- XML-RPC
- SOAP
- REST
- Network

**Comment by osrjv** [comment]
If you have a proposal or request for _new_ libraries, please comment them in this issue.

**Comment by TheRealRoboHeart** [comment]
Extending and improving the [SapGuiLibrary](https://github.com/frankvanderkuur/robotframework-sapguilibrary) would be great. It seems that it has not been maintained for a while.
https://github.com/frankvanderkuur/robotframework-sapguilibrary/issues

...and creating SAP RFC/BAPI libraries could be interesting to speed up.

**Comment by gustavogini** [comment]
Create a library to update Solidworks parts and assembly internal information.

**Comment by gustavogini** [comment]
Create a library to connect RPA Framework to openproject API.

**Comment by gustavogini** [comment]
Add to database library integration to nosql solutions for exemple neo4j.

**Comment by tonnitommi** [comment]
Closing this as new library ideas can be submitted as separate issues.
