### ISSUE TITLE
RPA.Database - log.html exposes database passwords (Security issue)

### ISSUE THREAD

**Issue by MitchK** [robocorp/rpaframework#874]
We noticed a security issue with `RPA.Database`. Even though we store our credentials in a Vault, the clear-text password is exposed in in the `log.html` output:

```
	INFO Connecting using : pymssql.connect(database=DBNAME,username=USERNAME,password=<PASSWORD>,host=HOST,port=1433,charset=None)
```

We connect to the database like so:
```
    secret = Vault().get_secret("database")
    db = Database()
    db.connect_to_database('pymssql',
                    secret["DB_NAME"],
                    secret["DB_USER"],
                    secret["DB_PASS"],
                    secret["DB_HOST"],
                    secret["DB_PORT"]
                    )
```

**Comment by tonnitommi** [comment]
Thanks for reporting; we'll look into is asap.

In the meanwhile, you can use `Register Protected Keywords` as a cure. Documentation is [here](https://robocorp.com/docs/libraries/rpa-framework/rpa-robotloglistener/keywords#register-protected-keywords).

**Comment by MitchK** [comment]
@tonnitommi Thanks for the workaround. Can you provide more information about the usage? I tried the following (in Python):

```
from RPA.RobotLogListener import RobotLogListener

...
    secret = Vault().get_secret("database")
    RobotLogListener().register_protected_keywords([secret["DB_PASS"]]) # or .register_protected_keywords(secret["DB_PASS"])
    db = Database()
    db.connect_to_database('pymssql',
                    secret["DB_NAME"],
                    secret["DB_USER"],
                    secret["DB_PASS"],
                    secret["DB_HOST"],
                    secret["DB_PORT"]
                    )

```

But the password is still not masked from the output.

**Comment by mikahanninen** [comment]
Thank you for the report @MitchK . I will check this one tomorrow as the library should be already suppressing the logging from the `Connect to Database` keyword. 

I expect that we can make the fix release on this one on Thursday.

**Comment by cmin764** [comment]
> @tonnitommi Thanks for the workaround. Can you provide more information about the usage? I tried the following (in Python):
> 
> ```
> from RPA.RobotLogListener import RobotLogListener
> 
> ...
>     secret = Vault().get_secret("database")
>     RobotLogListener().register_protected_keywords([secret["DB_PASS"]]) # or .register_protected_keywords(secret["DB_PASS"])
>     db = Database()
>     db.connect_to_database('pymssql',
>                     secret["DB_NAME"],
>                     secret["DB_USER"],
>                     secret["DB_PASS"],
>                     secret["DB_HOST"],
>                     secret["DB_PORT"]
>                     )
> ```
> 
> But the password is still not masked from the output.

Related to the temporary workaround, you can even use our helper wrapper `RPA.Robocorp.utils.protect_keywords` and you can see a usage example [here](https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Email/Exchange.py#L290).

In your case, this would be:
```python
protect_keywords("RPA.Database", ["connect_to_database"])
```
@mikahanninen we can use the same idiom in our library as well, although is no more different than what we do already with that helper, still have no clue why this happened by statically analysing the logs here in the thread.

**Comment by mikahanninen** [comment]
@MitchK Can you post the exact code (including the library import), because I can't reproduce the issue you posted. 

Using this code 
```robotframework
    Connect To Database    psycopg2    ${DATABASE}    ${USER}    ${PASSWORD}    127.0.0.1
    Log    Done.
```
the log looked like this
![database_logging](https://user-images.githubusercontent.com/1019528/223819567-e085a25f-0d49-4c12-a14b-60fd676e6529.png)

**Comment by MitchK** [comment]
@mikahanninen @cmin764 

> protect_keywords("RPA.Database", ["connect_to_database"])

This workaround did not work either. The password is still printed to the log.html:

```
from RPA.Database import Database
from RPA.Robocorp.Vault import Vault
from RPA.Robocorp.utils import protect_keywords

def verify_order_is_booked(key):
    protect_keywords("RPA.Database", ["connect_to_database"])
    secret = Vault().get_secret("database")
    db = Database()
    db.connect_to_database('pymssql',
                    secret["DB_NAME"],
                    secret["DB_USER"],
                    secret["DB_PASS"],
                    secret["DB_HOST"],
                    secret["DB_PORT"]
                    )
    orders = db.query("SELECT order_state as orderState FROM ORDER_UV WHERE order_key = " + str(key))
    if len(orders) == 0:
        raise Exception("No order found for key " + str(key))
    order = orders.to_dict()
    assert order["orderState"][0] == "BOOKED"

    db.disconnect_from_database()
```
<img width="1575" alt="Screen Shot 2023-03-08 at 4 51 25 PM" src="https://user-images.githubusercontent.com/2472064/223886756-cf27fada-2374-454a-ad79-68efa629f179.png">
