### ISSUE TITLE
Add `docutils` as a dependency to avoid libspec issues with LSP

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#88]
See https://github.com/robocorp/robotframework-lsp/issues/199

**Comment by osrjv** [comment]
I think this should be fixed in either RF or LSP, but let's keep this issue open for tracking.

**Comment by fabioz** [comment]
Added reply in: https://github.com/robocorp/robotframework-lsp/issues/199#issuecomment-735685186

**Comment by osrjv** [comment]
As a first fix, I will add docutils as a dependency to rpaframework. Will need to check if we should backport this to older releases as well.

**Comment by osrjv** [comment]
`docutils` is now a dependency in the latest patch release, `6.7.2`
