### ISSUE TITLE
`RPA.Browser.Selenium`: Click element when clickable

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#884]
It was reported by more than one customer that clicking certain elements produces the following error: `is not clickable at point (x, y). Other element would receive the click:`. Usually, this happens when the page element is found by Selenium to be in a different location (moved with a small offset) than it is actually displayed, thus a click over it will actually click something else inside Selenium's logic. (you can check this by taking a screenshot in order to see if the element image gets cropped)

@mikahanninen came with a `Selenium` extension which might overcome the struggle here, therefore we can introduce this into the library with a new keyword and support at the same time all locator strategies when working with such a keyword. (as currently it is limited to XPATH only)
[ExtendedSelenium.py.zip](https://github.com/robocorp/rpaframework/files/10963958/ExtendedSelenium.py.zip)

Internal Slack [thread](https://robocorptechnologies.slack.com/archives/CS71JM9T7/p1662369782610339)

**Comment by mikahanninen** [comment]
Just a note on the error "the element is not clickable" that it can be an intermittent error on a bot that might run 90% of the time just fine.
