### ISSUE TITLE
RPA.Assistant rows argument in Add text input

### ISSUE THREAD

**Issue by robot-tri-table** [robocorp/rpaframework#894]
I don't have the option to add rows in Add text input kewords

**Comment by xylix** [comment]
What sort of use case are you building exactly? (Just for context.) I will look into adding support for rows into next minor release of RPA.Assistant. Might add ability to specify both minimum amount of rows and maximum, to enable expanding textfields like like in below video.

https://user-images.githubusercontent.com/13387304/227915103-8be472e6-c225-4408-8be6-12aa789e023d.mov

**Comment by xylix** [comment]
Fixed in https://github.com/robocorp/rpaframework/pull/904/, release 2.2.0 coming soon.
