### ISSUE TITLE
RPA.WINDOWS  Click not successful but no error reported

### ISSUE THREAD

**Issue by hhsem** [robocorp/rpaframework#901]
I previously reported this problem in issue #806. You transfered me to the Troubleshoot forum. There I am asked to report it under issues.

I run a robot where I manually try to avoid that the robot becomes Top level.
This will cause the a "Click" is not successful because the robot has not the top level.
The problem is that my robot is not informed about the problem and no retry will take place.

Here you find a part of the Log-File if I do not disturb the robot:

KEYWORD RPA.Windows . Click ${Group}

Documentation:	Mouse click on element matching given locator.
Tags:	action, mouse
Start / End / Elapsed:	20230321 15:42:21.553 / 20230321 15:42:22.138 / 00:00:00.585
15:42:21.554 INFO Getting element with locator: WindowsElement(item=<uiautomation.uiautomation.TreeItemControl object at 0x0000024D59C80D30>, locator=None, name=‘SEMM02’, automation_id=‘’, control_type=‘TreeItemControl’, class_name=‘’, left=1018, right=1068, top=509, bottom=527, width=50, height=18, xcenter=1043, ycenter=518)

15:42:21.556 INFO Returning element: WindowsElement(item=<uiautomation.uiautomation.TreeItemControl object at 0x0000024D59C80D30>, locator=None, name=‘SEMM02’, automation_id=‘’, control_type=‘TreeItemControl’, class_name=‘’, left=1018, right=1068, top=509, bottom=527, width=50, height=18, xcenter=1043, ycenter=518)

00:00:02.167KEYWORD Output Tree Items ${Window}

Now I disturb the robot and you can see the problem for the “Click”:

KEYWORD RPA.Windows . Click ${Group}
[logNOT.zip](https://github.com/robocorp/rpaframework/files/11039507/logNOT.zip)

Documentation:	Mouse click on element matching given locator.
Tags:	action, mouse
Start / End / Elapsed:	20230321 15:51:32.832 / 20230321 15:51:32.844 / 00:00:00.012
15:51:32.835 INFO Getting element with locator: WindowsElement(item=<uiautomation.uiautomation.TreeItemControl object at 0x0000020500535CD0>, locator=None, name=‘Homebanking’, automation_id=‘’, control_type=‘TreeItemControl’, class_name=‘’, left=1037, right=1117, top=437, bottom=455, width=80, height=18, xcenter=1077, ycenter=446)
[logOK.zip](https://github.com/robocorp/rpaframework/files/11039509/logOK.zip)

15:51:32.839 INFO Returning element: WindowsElement(item=<uiautomation.uiautomation.TreeItemControl object at 0x0000020500535CD0>, locator=None, name=‘Homebanking’, automation_id=‘’, control_type=‘TreeItemControl’, class_name=‘’, left=1037, right=1117, top=437, bottom=455, width=80, height=18, xcenter=1077, ycenter=446)

15:51:32.844 INFO 2023-03-21 15:51:32.840 action.py[182] _click_element → Can not move cursor. TreeItemControl’s BoundingRectangle is (0,0,0,0)[0x0]. SearchProperties: {ControlType: TreeItemControl}

00:00:02.000KEYWORD Output Tree Items ${Window}

Can not move cursor. is reported ! But this information is not passed to the robot
(at least I can not find something)

you get the complet logs:

**Comment by cmin764** [comment]
Continuing the discussion here: https://github.com/robocorp/rpaframework/issues/913#issuecomment-1498842496
