### ISSUE TITLE
RPA.Windows Set_Value performs undesired validation for EOL inconsistency

### ISSUE THREAD

**Issue by magrosso** [robocorp/rpaframework#905]
I'm using set_value() to enter a floating point value into an edit text box. The UI does automatic validation AND correction on the entered value, i.e. the entered value is clamped to min/max values and the number of decimal places is normalized to 2 digits.
This validation and auto-correction is a UI feature we would like to test with RPA framework.

Unfortunataly _set_value_with_pattern() in action.py does its own validation by string-comparison of set-value against get-value and raising ValueError if they don't match (see code snippet below). I suppose this validation was meant to prevent OS-specific line-ending issues but also makes it impossible to test UI validation and auto-correction features.

I think, a test library should not validate on its own - at least not as a default!

Snippet from action.py: _set_value_with_pattern()```

```
if value_pattern.Value.strip() != new_value.strip():  # EOLs inconsistency
            raise ValueError(
                f"Element found with {locator!r} couldn't set value: {new_value}"
            )
```

```

**Comment by cmin764** [comment]
Will take care of it.

The default behavior is to ensure that something was at least written inside that box (and if that something equals the provided value). Will add a param with which you can either disable the validation or provide the expected value to compare against.

**Comment by magrosso** [comment]
Sounds good. Thanks.

**Comment by cmin764** [comment]
This should be [available](https://robocorp-developers.slack.com/archives/CH1GSKER0/p1680775293244119) with `rpaframework==22.5.0`.
