### ISSUE TITLE
Oauth2 from Microsoft

### ISSUE THREAD

**Issue by matheusbarcelos** [robocorp/rpaframework#925]
I need to develop the login in a test automation, where there is authentication in the second factor (oauth2) from Microsoft(Microsoft Authenticator).
I tried to develop using the RPA.MFA library, but I wasn't successful.
Studying the documentation I did not find any similar example.
Kindly, has anyone ever needed to implement something similar? Any libraries to recommend?

**Comment by cmin764** [comment]
- Here's an MFA example that includes Microsoft login as well: https://robocorp.com/portal/robot/robocorp/example-mfa-otp
- And if you're planning to use OAuth2 for e-mail sending with Exchange, we have another one: https://robocorp.com/portal/robot/robocorp/example-oauth-email
- Still related to Microsoft and the OAuth2 flow, we have the `RPA.MSGraph` library: https://robocorp.com/docs/libraries/rpa-framework/rpa-msgraph

If this is not really an issue with the library, I recommend closing this and opening a new thread on our troubleshooting [Forum](https://forum.robocorp.com/c/troubleshooting/15).

**Comment by matheusbarcelos** [comment]
Hello @cmin764 . Thank you for the informations

I checked the examples but didn't find a scenario similar to what I needed.

Our second factor authentication works as follows:
After entering user and password, the Microsoft Authenticator application receives a notification where it is possible to authorize or reject the login.

I followed the documentation present at https://robocorp.com/docs/libraries/rpa-framework/rpa-mfa, but I didn't find any examples that fit.
I see that I need to authorize the user, or get the access code to report at login.

Kindly, do you have any example similar to this case? Do you know if it is possible to automate login this way?

**Comment by cmin764** [comment]
Yes, please read the detailed instructions of this example [robot](https://robocorp.com/portal/robot/robocorp/example-mfa-otp) given the **Microsoft** section. Then download the bot and run [this](https://github.com/robocorp/example-mfa-otp/blob/master/tasks.robot#L22-L48) Microsoft task: `Microsoft MFA` which logins with user & password, then chooses to sign it through another way, then it submits the OTP code automatically without relying on your mobile Authenticator app anymore.

Robot code example:
```robotframework
Microsoft MFA
    # Login with username and password.
    Open Available Browser    https://mysignins.microsoft.com/
    Input Text When Element Is Visible    name:loginfmt    ${SECRETS}[microsoft_usr]
    ${submit_locator} =    Set Variable    idSIButton9
    Click Button When Visible    ${submit_locator}
    ${password_locator} =    Set Variable    passwd
    Wait Until Element Is Visible    ${password_locator}
    Input Password    ${password_locator}    ${SECRETS}[microsoft_pwd]
    Click Button When Visible    ${submit_locator}

    # Proceed to OTP input.
    Click Element When Visible    signInAnotherWay
    # Click Element If Visible    idA_SAASTO_SendCode
    Click Element When Visible    //div[contains(text(), 'verification code')]

    # Input OTP.
    Use Mfa Secret From Vault    MFA    microsoft_secret
    ${code} =    Get Time Based Otp
    Input Text When Element Is Visible    name:otc    ${code}
    Click Button When Visible    idSubmit_SAOTCC_Continue

    # Remember sign-in.
    Click Element When Visible    //span[contains(text(), 'show this')]
    Click Button When Visible    ${submit_locator}

    Go To    https://outlook.office.com/mail/
```

Make sure you have a correct [online](https://robocorp.com/docs/development-guide/variables-and-secrets/vault) / [local](https://github.com/robocorp/example-mfa-otp/blob/master/devdata/vault.yaml) Vault setup. (remove/rename _[env.json](https://github.com/robocorp/example-mfa-otp/blob/master/devdata/env.json)_ file when relying on an online Vault from Control Room (recommended))
