### ISSUE TITLE
Firefox unstable in headless mode

### ISSUE THREAD

**Issue by osrjv** [robocorp/rpaframework#93]
Intermittently when running Firefox in headless mode, it will crash with the message: `WebDriverException: Message: Failed to decode response from marionette`.

Related upstream issue: https://github.com/mozilla/geckodriver/issues/1559

**Comment by deeksha143** [comment]
Do we have any updates on this?

**Comment by mikahanninen** [comment]
Closed for now due to inactivity. Will be reopened if there is a need.
