### ISSUE TITLE
RPA.Cloud.Google Drive.py Move Drive File issue

### ISSUE THREAD

**Issue by oy-syousef** [robocorp/rpaframework#934]
### Problem:

Keyword "Move Drive File" in RPA.Cloud.Google doesn't work if file_id or file_dict are provided.
I looked into it and it appears that when passing file_id or file_dict, a call is made to the member function "_get_target_file" without passing the argument "details":
```
        if file_id or file_dict:
            target_files = self._get_target_file(file_id, file_dict, query, multiple_ok)
```
This will return only the file id as a string, which throws an exception later in the **move_drive_file**:
```
        for tf in target_files:
            try:
                file = self.service.files().get(fileId=tf["id"], fields="parents").execute()
```
Because **tf** is now a string and not a dictionary.

### Solution:
Call the _get_target_file with argument details=true
```
        if file_id or file_dict:
            target_files = self._get_target_file(file_id, file_dict, query, multiple_ok,details=True)
```

**Comment by oy-syousef** [comment]
I created a [PR](https://github.com/robocorp/rpaframework/pull/935) for this.

**Comment by mikahanninen** [comment]
PR has been completed and closed. Closing this issue also.
