### ISSUE TITLE
Please make rpaframework robotframework 6 compatible.

### ISSUE THREAD

**Issue by naibra** [robocorp/rpaframework#953]
rpaframework 23.0.0 requires robotframework!=4.0.1,<6.0.0,>=4.0.0, but you have robotframework 6.0.2 which is incompatible.
rpaframework-pdf 7.1.5 requires robotframework!=4.0.1,<6.0.0,>=4.0.0, but you have robotframework 6.0.2 which is incompatible.
rpaframework-windows 7.3.2 requires robotframework!=4.0.1,<6.0.0,>=4.0.0, but you have robotframework 6.0.2 which is incompatible.

**Comment by mikahanninen** [comment]
Hi @naibra . This under work at the moment ([PR](https://github.com/robocorp/rpaframework/pull/950)), but there is no timeline yet when we would be adding Robot Framework 6 support.

My guess is that we will have the support before July.

**Comment by naibra** [comment]
Thank you for your comment @mikahanninen. Will look forward to the support.

**Comment by Harm10** [comment]
I am also looking forward to rpa supporting version 6 as I have similar problems.

**Comment by cmin764** [comment]
Hi all, totally understand your concerns, and for an improved experience we can have this communication in one place: https://github.com/robocorp/rpaframework/issues/673
