### ISSUE TITLE
Include OAuth2 authentication flow for `RPA.Salesforce` library

### ISSUE THREAD

**Issue by TimothyLopas** [robocorp/rpaframework#993]
Some clients can only access the Salesforce Library with a token that is authorized through OAuth2. Can we enhance the keyword `Auth with token` to include OAuth2 capabilities? Or, if necessary, create a new keyword?

brief research:
This is the only mention of OAuth2 in the [simple_salesforce](https://github.com/simple-salesforce/simple-salesforce) package used by our library

If you have the full URL of your instance (perhaps including the schema, as is included in the OAuth2 request process), you can pass that in instead using instance_url:

Salesforce REST API developer guide: [About connected apps and OAuth2](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_oauth_and_connected_apps.htm?q=oauth2)

**Comment by cmin764** [comment]
Let's see if we can also use our built-in OAuth2 support right from `RPA.MFA` (the `* OAuth *` keywords). You can find a good example within `RPA.Email.common.OAuthMixin` used with both the **ImapSmtp** and **Exchange** libs.

**Comment by michaelconan** [comment]
If this is referring to the username-password connected app authorization flow:
- Our organization is also very interested in this functionality to replace current logic in a Gen1 solution
- The `simple-salesforce` package does not support this natively, but it can be implemented into `rpaframework` as show below:

```python
    def auth_with_connected_app(self, username: str, password: str, api_token: str, consumer_key: str, consumer_secret: str) -> None:
        """Authorize to Salesforce with security token, username,
        password, connected app key, and connected app secret 
        creating instance.

        :param username: Salesforce API username
        :param password: Salesforce API password
        :param api_token: Salesforce API security token
        :param consumer_key: Salesforce connected app client ID
        :param consumer_secret: Salesforce connected app client secret
        """
        self.session = requests.Session()
        res = requests.post(f"https://{self.domain}.salesforce.com/services/oauth2/token",
                      json={
                                "username": username,
                                "password": password + api_token,
                                "client_id": consumer_key,
                                "client_secret": consumer_secret,
                                "grant_type": "password",
                      }).json()
        self.sf = SimpleSalesforce(
            instance_url=res["instance_url"],
            session_id=res["access_token"],
            domain=self.domain,
            session=self.session,
        )
        self.logger.debug("Salesforce session id: %s", self.session_id)
```

@cmin764 is this in development or should we consider a PR?
