### ISSUE TITLE
`RPA.Cloud.Google.Send Message` problem with .xslx attachment

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#994]
### original error report:
> Hi all, I'm having trouble attaching an .xlsx to an email with RPA.Cloud.Google.Send Message. I'm able to attach a .txt but the .xlsx that arrives in the email appears to be corrupt.
In the screenshots you can see that both the .txt and .xlsx are attached in the email, and the .txt opens correctly, but the .xlsx "may be corrupted or the format is not compatible". I'm attaching the Config.xlsx, which is the same file I'm using for these tests (doesn't contain any sensitive data).
For what it's worth, in the past I've had similar issues attaching .xlsx files when I was playing around with Microsoft's Graph API and the solution ended up requiring the proper encoding of bytes if I remember correctly. My current issue has nothing to do with the Graph API but the error message is similar.

### analysis:
Problem is probably caused by the fact that .xlsx file's mimetype is ofc of "Application" type, but instead of using email.mime.application.MimeApplication class to attach it, it is being attached with email.mime.base.MimeBase class. The library has special handling for mimetypes text, image and audio, but all the other types fall under "base" type. Library should take care of all specific types.

**Comment by jaimes-alten** [comment]
Hi @mikahanninen, any news on this?

**Comment by mikahanninen** [comment]
Back from my vacation. I hope to get this into this week's release.
