### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by balajee-ha** [robocorp/rpaframework#999]
SeleniumLibrary doesn't have a keyword by name 'Set Element Attribute' however the documentations below incorrectly mention them as part of this library and need to be corrected.

https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-selenium/keywords#set-element-attribute
https://rpaframework.org/libraries/browser_selenium/index.html

**Comment by mikahanninen** [comment]
Hi @balajee-ha . The documentation unfortunately only shows the latest version documentation. Which version of  `rpaframework` you are using ?
